### ISSUE TITLE
Ajustements dans Explore/brood

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#100]
Selon les annotations décrites ci dessous
1/ charte graphique des couleurs pour le boutonn apply
2/ la flèche est coupée (sur tous les devices)
3/ la date est coupée
4/ déplacer 1 year en dessous de 9 month
4.1 / enlever le pluriel de toutes les plages (**1 day** au lieu de **1 days** c'est aussi accepté et plus sobre). même chose avec month au lieu de months
5/ aligner les plages prédéfinies avec la marge gauche
6/ raccourcir le graphique en X pour laisser de la marche à droite et de la place pour les tools. 

![Capture d’écran   2019-12-29 à 12 58 57](https://user-images.githubusercontent.com/41069288/71742546-743c4100-2e62-11ea-8172-a26ba647d6c3.png)

**Comment by savioarthu** [comment]
1, 3, 4, 5  ok

Pt 2 -> flèche toujours légérement coupée (celle de gauche)
Pt 6 -> Il faut encore un peu de marge à droite, les tools sont de mon côté en partie sur le graphe.

**Comment by savioarthu** [comment]
Je ferme car ce qu'il reste à faire est dans l'issue #113 !
