### ISSUE TITLE
Astronomie

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#101]
Dans Explore les phases de la lune sont toujours en anglais. 
1/ Il faudrait activer les traductions.

En plus de cela, voici quelques améliorations suggérées par DominiqueT
2/ déplacer la lune au calendrier central, celui des événements car mélangée avec la météo elle n'est pas visible.
3/ ajouter dans le menu contextuel, en plus des phases de la lune les paramètres suivants
- lever du soleil / sunrise
- coucher du soleil / sunset
- durée du jour (coucher-lever) 

Avec tout ça il va falloir peut être changer le picto pour mettre un démi soleil/demi lune. Je l'ajoute à l'issue de la màj des pictos. en attendant on garde l'actuel.

**Comment by savioarthu** [comment]
Tout est dispo dans mongo.
Date -> Date du jour
Phase_name -> phase de la lune. @mickael2407  gérera la trad sur le web. 
Ascendant -> booléen 1 ou 0 si période ascendante -> période bleutée

Dans sys on a sunrise et sunset correspondant au coucher et lever de soleil en UTC. 
 Ainsi duree du jour (heures) = sunset-sunrise basiquement. @mickael2407  ça t'arrange que je crée une nouvelle variable ou ça te suffit comme ça ?

<img width="388" alt="Capture d’écran 2020-01-07 à 20 26 42" src="https://user-images.githubusercontent.com/49641714/71922839-09ee0e00-318c-11ea-9616-90eaed1f7983.png">

Pour la traduction j'ai retrouvé quelque chose qu'on a déjà fait. Du coup, à la place de phase_name je mettrais le code et tu récupéreras le trad en fonction de l'utilisateur @mickael2407 , ça te va ? 
[Moon.json.zip](https://github.com/mellisphera/mellisphera-web/files/4032142/Moon.json.zip)

**Comment by savioarthu** [comment]
Il y a un icône qui ne passe pas pour l'Astro

<img width="336" alt="Capture d’écran 2020-01-09 à 10 15 07" src="https://user-images.githubusercontent.com/49641714/72054287-fc8a6e00-32c8-11ea-992b-aa4adce499fc.png">

**Comment by mickael2407** [comment]
@savioarthu oui ok pour les code du coup je vais attendre ca pour la trad

**Comment by savioarthu** [comment]
@mickael2407 et pour la durée du jour, pas de soucis pour toi de le faire sur le web en faisant sunset-sunrise ? Pas besoin d'un nouveau champ normalement ?

**Comment by savioarthu** [comment]
Fait, voici la trad
[Moon.json.zip](https://github.com/mellisphera/mellisphera-web/files/4052553/Moon.json.zip)

**Comment by savioarthu** [comment]
Tout fonctionne !
