### ISSUE TITLE
Améliorations pour les alertes - settings

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#102]
Après discussion avec Rich et Theo quelques petits ajustements pour être au point

1/ par défaut les alertes sont off (éviter le spam) donc avec champs email vides et bouton off
2/ les boutons des autres pages ils sont comment quand le bouton dans settings est Off? => grisés?
3/ ajouter un bouton "send test email" pour envoyer un email de vérification (je ne sais pas si c'est facilement réalisable..)

4/ et bien sûr réduire la plage de texte pour saisir l'email et le bouton on/off => utiliser la meme largeur de div que dans les autres pages des alertes => le bouton doit être au même endroit

![Capture d’écran 2020-01-07 à 23 43 01](https://user-images.githubusercontent.com/41069288/71935851-29932f80-31a8-11ea-8bbb-7989e535c213.png)

**Comment by savioarthu** [comment]
Reste:
1. Majuscule à 'Other' -> mettre en minuscule 'other'
2. Mettre en 'Off' pour tous les utilisateurs de base.
3. Ajouter un test 'send test email' -> par contre @lzpons comment tu veux le gérer ça ? Parce que ça peut être un booléen qui passe à 1 dans mongo et je le récupère et j'envoie le mail et ça repasse à 0. etc. Mais ça serait pas automatique (maximum dans les 30 minutes à venir).
@mickael2407  une autre idée ?

**Comment by lzpons** [comment]
l'envoi devrait être instantané, on s'attend tous à ça non?

**Comment by savioarthu** [comment]
Evidemment mais je ne vois pas comment faire pour que ça soit instantané à partir d'un script de la data

**Comment by mickael2407** [comment]
Sinon en passant par le websocket c'est possible non

**Comment by savioarthu** [comment]
En cliquant sur le bouton, tu peux appeler un script simple qui envoie un mail directement ? Si oui, le script est simple à faire.

**Comment by mickael2407** [comment]
oui comme on fait pour l'update des données

**Comment by savioarthu** [comment]
Ok je m'occupe de faire le petit script ce week end. Tu pourras ajouter le bouton 'Send test email' avec message de confirmation après en début de semaine pro ;)

**Comment by savioarthu** [comment]
[TestEmail.zip](https://github.com/mellisphera/mellisphera-web/files/4050779/TestEmail.zip)

Voila le script d'envoi d'un mail test en format websocket (prend userId en paramètre).

**Comment by savioarthu** [comment]
fonctionne ;)
