### ISSUE TITLE
Certaines photos glissées/deposées se tournent de 90°

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#103]
En déposant qq image sur le fond du rucher on en voit certaines (prises avec le telephone?) qui se retournent de 90°.
Il y a certainement un paramètre qui est pris en considération. Faudra l'identifier.

Prio 2 pour l'instant.

**Comment by mickael2407** [comment]
Je pense que la photos à été prise en portrait

**Comment by savioarthu** [comment]
Idem pour cette issue @lzpons , pas priorisé finalement.

**Comment by lzpons** [comment]
pas de retour client, on oublie.

**Comment by lzpons** [comment]
Je rouvre cette issue car le problème persiste. 

Il faut évaluer pourquoi les images se retournent (smartphone) et éventuellement ajouter des contrôles pour que l'utilisateur (qui sait quelle est la bonne position la choisisse lui même. mais le mieux serait partir de l'image à l'endroit sur le desktop

quelques tests à réaliser.

celle ci à l'origine était retournée 180% pieds vers le haut. Je l'ai déchargée de mellisphera et retournée avec Apperçu.
elle est à l'endroit maintenant
![retouchee](https://user-images.githubusercontent.com/41069288/98368279-5f5aac00-2037-11eb-8c0f-bb96dd0fccc2.jpeg)

**Comment by lzpons** [comment]
éventuelle solution, qui me semble très plausible : ici 
https://stackoverflow.com/questions/43253889/imagemagick-convert-how-to-tell-if-images-need-to-be-rotated/43255462
