### ISSUE TITLE
Pas de Fitness alors qu'il y a tout pour le sortir?

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#104]
A/ La ruche L01 de Theo affiche pastille blanche alors qu'il y a de la donnée de couvain et de poids. A voir si c'est dans le calcul ou dans l'affichage.

B/ le 25/12 on a également une case rouge. Il n'y a pas eu de données sur le capteur dans le corps et on a pris celles du capteur de la hausse. C'est prio 2 pour cela car tout le monde ne traine pas 2 capteurs/ruche, mais bon a savoir.
En regardant leurs données j'ai pu comparer comment MBM ne raccorde pas les points manquants alors que MS le fait et donc ce type de soucis est moins identifiable chez nous.

Je vous laisse vous départager. 

![Capture d’écran 2020-01-07 à 23 18 45](https://user-images.githubusercontent.com/41069288/71936270-395f4380-31a9-11ea-8b8c-cdb68a8e3693.png)

![Capture d’écran 2020-01-07 à 23 08 17](https://user-images.githubusercontent.com/41069288/71936353-7a575800-31a9-11ea-880f-6c56349b6cc9.png)

![Capture d’écran 2020-01-07 à 23 07 20](https://user-images.githubusercontent.com/41069288/71936355-7b888500-31a9-11ea-8c79-23f3513486c3.png)

**Comment by savioarthu** [comment]
A) Ca venait de moi, une condition oubliée, c'est corrigé, je déploierai plus tard mais j'ai mouliné quand même pour Théo en attendant que ça soit déployé. Je pense que c'est bon mais aucun moyen de vérifier sur admin car le modèle Bfit n'est pas encore implémenté en admin.

**Comment by lzpons** [comment]
Ok j’ai demandé à Théo de vérifier

**Comment by savioarthu** [comment]
J'ai déployé le correctif

**Comment by mickael2407** [comment]
C'est fait .

**Comment by lzpons** [comment]
ok, parfait!
