### ISSUE TITLE
Reconnexion toujours ko à la premiere tentative

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#105]
Lorsqu'on se déconnecte (log out) et on se reconnecte dans la foulée, on trouve le sablier qui tache de trouver ses esprits.
Seule manière de sortir de l'impasse: recharger la page, ce qui passe par une autre erreur (page not found) et se termine par une resaisie de l'url sans sa deuxieme partie après le .com/ 

L'erreur est systématique, sur firefox et chrome. Je l'ai vue également chez Rich. 
C'est peut être lié à la réutilisation du token?

![Capture d’écran 2020-01-09 à 00 22 54](https://user-images.githubusercontent.com/41069288/72024915-f8cdfb80-3276-11ea-9701-d5c64bdc90ea.png)

**Comment by mickael2407** [comment]
Je pense avoir corrigé à vérifier !

**Comment by savioarthu** [comment]
Pour moi, ça a l'air de fonctionner, j'attends confirmation de @lzpons pour fermer.

**Comment by lzpons** [comment]
J'ai fait plusieurs fois la manip et effectivement c'est bien plus robuste que la veille.
On ne saura pas ce que c'était (@mickael2407 etant un peu avare en commentaires :) ) mais le resultat est très bien.

je ferme
