### ISSUE TITLE
Appliquer la charte graphique pour les tableaux de notes

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#106]
Dans le tableau des notes tout est bleu marin alors que nous n'avons pas ce couleur dans notre charte. 

1/ Proposition de mettre 
- du gris clair sur le trait de pourtour
- du gris antracite dans la barre supérieure du tableau
- des boutons "edit" et "+" en vert comme pour les autres bouttons 
ça s'applique aux deux tableaux de notes : apiary et hive

![Capture d’écran 2020-01-09 à 22 19 28](https://user-images.githubusercontent.com/41069288/72105587-1d38df00-332e-11ea-8124-9bfe20db9135.png)

2/ Au passage si on peut faire sauter cet intervalle etre la barre de titre du tableau et la première note ce serait trop beau.

3/ Aligner egalement sur la verticale le "+" avec les boutons "edit"

**Comment by savioarthu** [comment]
Tout est ok pour moi.
