### ISSUE TITLE
Ajustements de format

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#108]
Voici quelques ajustements nécessaires pour que l'expérience utilisateur soit le plus fluide possible

1/ aligner les boutons avec les champs de saisie
![Capture d’écran 2020-01-14 à 21 52 08](https://user-images.githubusercontent.com/41069288/72382000-a712ee80-3718-11ea-8739-b18c7e34c435.png)

2/ Every => minuscule
![Capture d’écran 2020-01-14 à 21 53 05](https://user-images.githubusercontent.com/41069288/72382030-b72ace00-3718-11ea-880e-08e28f8963d1.png)

3/ éviter ces grandes etendues qui font penser au far west. Garde les dimensions même si la moitié de l'écran reste vide sur des 27" on s'en fiche. 
3.1/ bien sûr utiliser les mêmes largeurs pour les trois pages 
![Capture d’écran 2020-01-14 à 21 53 27](https://user-images.githubusercontent.com/41069288/72382050-c3af2680-3718-11ea-87a3-a607203d0e8c.png)

4/ rapprocher les moyennes du calendrier (diviser par deux la distance). On avait dit qu'on faisait sauter la deuxième ligne "last 7 days" car parfois c'est pas la dernière semaine...

![Capture d’écran 2020-01-14 à 21 54 15](https://user-images.githubusercontent.com/41069288/72382315-4cc65d80-3719-11ea-8a55-1afdf0b898b9.png)

5/ enlever la frange rendra plus lisible le tableau
![Capture d’écran 2020-01-14 à 21 54 39](https://user-images.githubusercontent.com/41069288/72382331-53ed6b80-3719-11ea-8c24-273703124dc3.png)

**Comment by savioarthu** [comment]
Pendant que nous sommes dans les détails, tout avec un 's' et non un 't' et jour(s) à la place de jour ;)

![Uploading Capture d’écran 2020-01-15 à 11.00.48.png…]()
