### ISSUE TITLE
Ajustements de format #2

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#109]
Alertes
1/ lier le on des settings aux autres on de chaque alarme. Si le general est off les autres ont grisés.
2/ texter test email en espagnol "probar email" et aligner bouton "test email" avec 2eme case email
3/ en espagnol "cia" => día
4/ en espagnol configuraciones => configurar
5/ en espagnol météo => meteo
11/ mettre les (i) en gris anthracite comme pour les "?"
12/ changer le libelle de l'alerte de gain rapide de poids "increased 3kg" par "gained more than 3kg". Autrement c'est pas cohérent avec la bulle de productivité.

Apiary
6/ infobulle avec même format que cadenas : blanc sur fond gris anthracite
quelques ajustements
9/ récupérer notes de MBM au format brut, expurger les balises html
10/ sur la sidebar mettre la zone selectionnée en couleur vert foncé (au lieu de blanc) et avec un carré sans coins arrondis
11/ les noms sous les pastilles sont highlightés au survol, mais ils ne sont pas actifs. donc pas besoin de les changer de couleur au survol. les laisser statiques.
 
Explore
7/ lever/coucher du soleil avec heure seulement
8/ remplacer "duration of the day: 9h7m" par "daylight: 9h 7m" (j'ai changé d'avis, vous aviez raison : si on met 9:07 c'est vraiment une heure et non pas une durée.)

**Comment by savioarthu** [comment]
Je me permet de rajouter en français -> 'Envoyer' à la place de 'Envoyez'.
Et si possible dans toutes les langues ajouter 'jour(s)', 'dia(s), 'day(s)' avec le s.
Que des détails again.

<img width="211" alt="Capture d’écran 2020-01-16 à 22 24 28" src="https://user-images.githubusercontent.com/49641714/72564039-33571a00-38af-11ea-9b35-e6c10b51b088.png">

**Comment by lzpons** [comment]
Je vais aller un poil à contre courant d'@Arthur. Je pense que les (s) alourdissent l'affichage. c'est plus précis certes, mais un peu encombrant. Je suis pour laisser au singulier. ici comme dans les unités des alertes.

**Comment by savioarthu** [comment]
Laissons donc au singulier, ça fera moins de boulot pour mickael ;)

**Comment by mickael2407** [comment]
Les points Alertes & Explore sont finis manque Apiary

**Comment by savioarthu** [comment]
Vérification : 
Pt 1) 2) 3) 4) 5) 6) 8) 11) 12) ok
Pt 9) 10) 11) pas commencé donc normal

Pt 7) 
Manque la majuscule à 'daylight' -> 'Daylight' 
Enlever date et ne garder que l'heure pour les champs Sunrise & Sunset (lever/coucher de soleil)

Ajout Alertes
Mettre à jour avec les nouveaux icônes.

**Comment by savioarthu** [comment]
Tout semble ok !

Il manque toujours :
1) Dans 'Alerts' -> remplacer 'Envoyez chaque' par 'Envoyer chaque' 
2) Dans Astro 
a) Manque la majuscule à 'daylight' -> 'Daylight' en EN 
b) Enlever année et mois : ne garder que l'heure pour les champs Sunrise & Sunset (lever/coucher de soleil)

**Comment by savioarthu** [comment]
Good
