### ISSUE TITLE
Brancher le Fitness dans Explore

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#111]
remplacer le picto "poids total" du premier calendrier par un picto "fitness" et lui affecter le champ associé avec le message correspondant.

**Comment by savioarthu** [comment]
Icône ok, plus qu'à charger le calendrier

**Comment by savioarthu** [comment]
On en a parlé avec @mickael2407, c'est pas quelque chose qui manque aux utilisateurs pour l'instant. Le Fitness sera super intéressant quand on aura implémenté l'algorithme final ruche morte/ruche en grand declin/ruche très faible sans couvain qui est encore en test mais qui j'espère sera lancé en prod bientôt. Cela devrait tomber au même moment que matériel, c'est pourquoi je déplace cette issue dans v2.3 Matérial.

**Comment by lzpons** [comment]
ok, je suis d'accord c'est le plus pertinent.

**Comment by lzpons** [comment]
Besoin de cet indicateur pour pouvoir évaluer le comportement et cohérence des algos sur chaque ruche, qui parfois vont et viennent soit par manque de données soit par fluctuations T. ça manque pour l'analyse
