### ISSUE TITLE
Ajustements après revue génerale

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#113]
Test avec ipad
APIARY
- le "+" pour les notes est a moitié masque à droite (seulement ipad vertical)
- changer bouton "sensor" par "device"
- clic sur le sensor id masque sa ref et laisse la boite grise vide
- les (?) des calendriers sont en déhors du cadre et en déhors de l'espace couvert par les barres supérieures
![IMG_6EAA369AFD79-1](https://user-images.githubusercontent.com/41069288/72598828-e0ae4a00-3910-11ea-8459-3966cd4132b7.jpeg)
- user picture couleur vert mellisphera au lieu de bleu

SETTINGS 
- mettre une marge entre les encarts et la side bar. Même largeur qu'entre la photo de Apiary et la side bar. En gros faire flotter les différents encarts, comme dans mbm/configure

EXPLORE
** HIVE
- le calendrier de poids max est marqué comme "gain max" au lieu de "max weight". 
- on a encore la flèche gauche de la date qui est amputée

** BROOD
- le graph ne rentre toujours pas et les tools pour zoomer empiètent. Sur ipad il n'y a pas de marge et on peut pas scroller avec le doigt => le faire sensiblement moins large
- l'aide (?) est planquée, en dehors du cadre => il faut la faire apparaitre
- sur ipad la barre en bas n'apparait pas non plus (ou tres peu)

ALERTS
- send test email : ecrire une confirmation "email sent!"
- déplacer l'alerte "weather station problem" de Weather => Sensor et la renomer "weather station disconnected"
- changer le bouton "sensor" par "devices"

**Comment by mickael2407** [comment]
La confirmation ne fonctionne pas sur safari

**Comment by savioarthu** [comment]
J'ai testé sur iPad (Safari) et Mac (Safari et Chrome), toutes les modifs uniquement sur iPad sont ok pour moi. Pour Brood, tout est ok aussi !
Après vérification de tous les autres points un par un, voici ce qu'il reste:

**Apiary :
-Remplacer 'Sensor' par 'Device'

**Alerts:
-Remplacer 'Sensor' par 'Device'
-Ajout : mettre une majuscule à 'Weather station disconnected' pour uniformiser le tout.

**Explore:
-Sur mon écran mac en plein écran (15 pouces) et sur min ipad Pro (9), j'ai la flèche de gauche qui est toujours amputée. Bon d'accord c'est un détail, si tu n'y arrives pas c'est pas grave.

**Settings :
-Faire flotter les encarts comme dans MbM 'Configure' (Espacer chaque encart par un espace)
<img width="1444" alt="Capture d’écran 2020-02-06 à 18 34 47" src="https://user-images.githubusercontent.com/49641714/73962885-89980580-490f-11ea-83fc-3e7b72fb16d9.png">

**Général:
-Vérifier requête météo temp/hum mini maxi, ça charge dans le vide sur tous les navigateurs et Os de mon côté. 
-L'user picture ennemi haut à gauche -> couleur vert mellisphera au lieu du bleu actuel.

**Comment by savioarthu** [comment]
Apiary, Alerts, Settings OK

A priori les flèches on s'en fiche pour l'instant donc je passe mais il reste plus qu'un dernier point :

1) L'user picture en haut à gauche -> couleur vert mellisphera au lieu du bleu actuel.
