### ISSUE TITLE
Gestion de plusieurs capteurs T2/TH sur une même ruche

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#115]
Il faut voir comment gérer le cas de plusieurs capteurs T2 ou TH sur une même ruche. 
Le plus simple est de regarder comment c'est fait avec le calendrier des poids et laisser choisir l'utilisateur quel capteur il veut afficher sur les calendriers pour ses ruches. 

A voir comment gérer cette gestion.

**Comment by lzpons** [comment]
Peut être une solution envisageable est de placer les deux séries en dessous du graphique soit avec al réf capteur soit (encore mieux) avec leur position dans la ruche

![Capture d’écran 2020-01-25 à 15 44 55](https://user-images.githubusercontent.com/41069288/73122858-c405b800-3f89-11ea-8951-f40cef52a494.png)

**Comment by lzpons** [comment]
Je vois le resultat, c'est un bon point de départ et je te propose les modifs suivantes
1/ ajuster un peu la distance au calendrier (rapprocher) 
2/ sais-tu afficher la position du capteur dans la ruche "under lower brood ..." en plus de son ID?
3/ rien à voir mais dans le selecteur de dates il manque "2 month", à chaque fois j'ai envie de prendre cette échelle de temps et suis coincé entre 1 et 3 mois.

**Comment by savioarthu** [comment]
1) OK
2) Voir la possibilité
3) Il faut ajouter "2month" dans le choix de la période entre 1 et 3 month

Petite question pour @lzpons aussi :

Ce que tu as fait pour les capteurs dans le calendrier Brood dans Apiary, pourquoi ne pas faire pareil pour le calendrier des poids juste en dessous avec un choix des capteurs ?

<img width="320" alt="Capture d’écran 2020-02-07 à 13 14 25" src="https://user-images.githubusercontent.com/49641714/74028906-cc0f2000-49ab-11ea-9d23-bcdaae546eb6.png">

**Comment by lzpons** [comment]
en phase avec la proposition. On a décidé de garder tous les titres en haut des calendriers (assez près) et toutes les légendes/series/maps en dessous.

**Comment by savioarthu** [comment]
C'est ok je ferme.
Quand à la selection de ruche par rapport à son emplacement, on verra plus tard, on ouvrira une issue pour ça !
