### ISSUE TITLE
Gérer les fuseaux horaires pour les DOM hors métropole

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#116]
A priori pour l'instant on associé les territoires d'outre mer au fuseau CET et donc avec l'heure métropolitaine?

A voir quelle est la solution la plus pertinente, mais peut être il faudra un ménu déroulant pour le choix du fuseau comme dans MBM.

**Comment by savioarthu** [comment]
@mickael2407 Le soucis vient de la data ?

**Comment by savioarthu** [comment]
@lzpons as-tu des news pour le fuseau horaire ?

**Comment by lzpons** [comment]
la dernière info date de la semaine dernière avec le mail de JMB. Pas de news depuis.

**Comment by savioarthu** [comment]
JMB problème résolu (cf mail et slack).
Cela devait déjà être traité normalement, je ne sais pas ce qu'il s'est passé mais c'est ok. Si un nouveau problème de ce côté arrive, on rouvrira cette issue et peut-etre qu'on mettra en place un système de fuseau à choisir comme sur BM.
