### ISSUE TITLE
Note explicative dans les alertes

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#118]
suite à la question de Dan, faire évoluer l'interface ainsi
(ne pas oublier astérisque à côté de "Send every* " ) 

![Capture d’écran 2020-01-24 à 10 10 31](https://user-images.githubusercontent.com/41069288/73057624-48750f80-3e92-11ea-84d9-71c6975d032d.png)

**Comment by savioarthu** [comment]
Il manque le '*' à coté de 'Envoyer chaque'.

<img width="548" alt="Capture d’écran 2020-01-25 à 17 23 58" src="https://user-images.githubusercontent.com/49641714/73124096-7d1ebf00-3f97-11ea-86dd-913811891496.png">

Pour le texte en français je mettrai plus : 'les emails sont envoyés uniquement lorsque des alertes ont été détectées'.
Et la couleur, peut-etre changer aussi ?

Qu'en penses-tu @lzpons  ?

**Comment by lzpons** [comment]
Astérisque: je l’avais écrit!
Couleur : charte graphique!!! Donc gris
Texte fr : notre belle langue devrait permettre de faire une phrase succincte et pleinement compréhensible en 4 ou 5 mots?

**Comment by savioarthu** [comment]
Vous en avez discuté ensemble @lzpons et @mickael2407 ? 
Rouge ou gris du coup ? Actuellement c'est rouge.
J'aime bien en rouge mais je connais cette histoire de charte graphique et vu le précédent message, je demande avant de fermer l'issue. Si on laisse en rouge par contre faut mettre l'astérisque en rouge aussi à côté du texte.

**Comment by lzpons** [comment]
gris!

**Comment by savioarthu** [comment]
Toujours pas en gris :(

**Comment by mickael2407** [comment]
Il manqué la couleur sur les listings des alertes c'est ok

**Comment by savioarthu** [comment]
Oui mais ici c'est encore en rouge !

<img width="403" alt="Capture d’écran 2020-01-31 à 13 09 25" src="https://user-images.githubusercontent.com/49641714/73538286-ec2e6480-442a-11ea-95e4-9151be526b9e.png">

**Comment by mickael2407** [comment]
ah mais même le warning en gris ?

**Comment by savioarthu** [comment]
Yes tout même le texte faut le passer en gris
