### ISSUE TITLE
Dernier jour sur le calendrier n'est pas affiché

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#120]
Pour une selection quelconque de plage de dates dans Explore on a systématiquement le dernier jour de ladite election qui ne se remplit pas

![Capture d’écran 2020-01-28 à 21 10 50](https://user-images.githubusercontent.com/41069288/73301320-d7778400-4212-11ea-8f5c-e78585d2742e.png)

![Capture d’écran 2020-01-28 à 21 12 20](https://user-images.githubusercontent.com/41069288/73301350-e6f6cd00-4212-11ea-8c62-f09abcfa8ea4.png)

**Comment by savioarthu** [comment]
Ok !
