### ISSUE TITLE
Ajouter export listing PDF/XLS du rucher

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#123]
Pour pourvoir aller sur le rucher avec un document de référence et de prise de notes également.

**Comment by savioarthu** [comment]
Pour moi ça fonctionne. A voir avec @lzpons ce qu'il veut comme info. Si c'est ok comme ça on fermera

**Comment by lzpons** [comment]
Après en avoir discuté avec Mickael vendredi on arrive à la conclusion qu'il faut exporter un xls et non un pdf. Simplement parce que avec les filtres on peut trier les ruches comme on veut (alphabétique, %couvain, etc.

Donc la spec serait 
1/ Sortir un excel avec hivename / brood % / weight / sensors list / observations /
Juste cela, ensuite on verra à l'usage.

**Comment by savioarthu** [comment]
Good j'aime bien. Bon ça me sort un csv ? 

Juste un détail, ça me sort toutes les ruches de tous les ruches. Il faut uniquement celui du rucher actif et peut-être pas prendre toutes les notes mais uniquement celles du dernier mois ? 
@lzpons 

![Capture d’écran 2020-02-10 à 16 08 42](https://user-images.githubusercontent.com/49641714/74161741-bd30a380-4c1f-11ea-8505-41f74059f3b1.png)

**Comment by lzpons** [comment]
je ne vous l'avais pas précisé pour ne pas surcharger la demande, mais je verrais bien un rucher par onglet excel 😅
ce serait super easy comme ça, d'un clic on exporte tout et ensuite on le travaille avant d'aller au rucher.

Pour les notes, gardez tout dans l'ordre antichronologique. On pourra toujours réduire la hauteur des rangées. Seulement, je remaque qu'il manque les dates des notes. Sans ça on n'en fait rien.

**Comment by mickael2407** [comment]
Pour les onglet je ne peut rien faire c'est le logiciel qui géré ca

**Comment by savioarthu** [comment]
Après discussion ce matin  + Mickael en début d'aprem:

-Ajout date de l'export sur colonne + nom [FAIT]
-Retrait du titre [EN COURS]
-Ajout d'une colonne Apiary [FAIT]
-Conservation des 5 notes pour chaque ruche [EN COURS]

**Comment by savioarthu** [comment]
Suite réunin ce matin:
1) Ajouter date dans le nom du fichier
2) Faire en sorte que les délimiteurs fonctionnent avec retour charriot sur Excel
3) Mettre la batterie dans une colonne à part avec le bon % en face du bon capteur

**Comment by savioarthu** [comment]
Sur mac Ok avec Numbers et excel (en exportant à partir de numbers), window aussi vu ce matin sur Excel. Fonctionne avec Libro Office Excel sur Linux ok.

<img width="1201" alt="Capture d’écran 2020-02-18 à 17 03 03" src="https://user-images.githubusercontent.com/49641714/74753550-9225ff80-5270-11ea-8e72-1fc59d46d59d.png">

1. Date nom fichier ok
2. On peut pas faire mieux c'est ok
3. Batterie ok
4. Tri rucher et ruche ok
5. A compléter plus tard quand j'aurais classer les versions 

Je ferme
