### ISSUE TITLE
Mini ajustements de l'interface et Admin

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#124]
Quelques petits détails a ajuster

1/ mets le logo mellisphera blanc sur la barre d'en haut (blanc sur fond gris, exactement comme sur la page de login mais avec lettres seulement

2/ à la connexion avec compte Admin, aterrir comme toujours dans Apiary et non pas dans admin

3/ déplace le picto admin tout en bas de la sidebar pour qu'on puisse garder les mêmes habitudes.
 
![Capture d’écran 2020-02-04 à 22 17 45](https://user-images.githubusercontent.com/41069288/73787850-58e38f00-479c-11ea-9037-3f901f68fd78.png)

**Comment by savioarthu** [comment]
Update: Pt 2 et 3 ok. Ne reste que le premier point, le logo a été choisi la semaine dernière, plus qu'à le placer et ça sera good.

**Comment by savioarthu** [comment]
@mickael2407 cette issue est vieille, que reste-il à faire pour la fermer ? 

J'ai l'impression que les points 1 et 2 sont ok et qu'il ne reste quel le pt3, non?
