### ISSUE TITLE
Comment transite le champ "description" de la ruche de MBM à MS?

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#125]
avons nous accès à ce champ dans MS?
pourrait-il apparaitre en survolant le label de la ruche sur Apiary?

**Comment by mickael2407** [comment]
C'est fait mais j'ai fait la correction sur la même version pour le transfert d'une ruche donc j'attendrais que cela sois en prod pour déployer.

**Comment by lzpons** [comment]
On a convenu ce matin avec mickael qu'on afficherait cette description sur l'entete du tableau des notes de la ruche

**Comment by savioarthu** [comment]
Fonctionne
