### ISSUE TITLE
Réduire les pictos sur téléphone

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#126]
Sur smartphone les pictos ne réduisent pas de taille et ça fait très massif. Peut-on les réduire en conséquence?

Aussi la pastille du hub a le symbole wifi décalé.

![IMG_5077](https://user-images.githubusercontent.com/41069288/74087374-e0c2e500-4a8b-11ea-9ca9-c50de33a853c.PNG)

**Comment by savioarthu** [comment]
Good
