### ISSUE TITLE
Implementer le déplacement des ruches d'un rucher à un autre

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#127]
tout est dans le titre. C'est plus subtile de ce qu'il parait à première vue. C'est pourquoi il faut qu'on fasse atention avant de se lancer.

Une ruche qui change de rucher va amener avec elle la météo qu'elle a vue ainsi que les observations et anotations et les capteurs également. Amanda propose une structuration differente du json et il faut lui répondre après avoir analysé ce que ça peut donner chez nous.

**Comment by savioarthu** [comment]
C'est déployé par amanda, normalement c'est ok de notre côté, on rouvrira si problème
