### ISSUE TITLE
Amélioration du login

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#129]
J'ai eu un client au teléphone tout à l'heure et on en a tiré quelques suggestions d'amélioration par rapport au login.

Il n'avait pas compris que le compte de test n'était pas le sien.
1/ changer le libellé du bouton gris "compte démo", "démo account"
2/ dans le compte demo mettre un popup à la connexion qui indique "Vous pouvez explorer mellisphera avec ce compte de démo. Toutes vos modifications sont effacées dans les 24h"
3/ enlever la possibilité de basculer sur mybroodminder (masquer l'icone?) car dans ce cas il peut être troublant de naviguer sur un autre compte que le test

4/ dans la page de login le lien "creer un compte" pourrait s'appeler "creer un compte MyBroodminder".
5/ possibilité de basculer automatiquement sur l'onglet s'inscrire? sur MBM? 
ils sont troublés par cette bascule. Ils pensent creer un cpte sur MS et ils atérrissent sur MBM

6/ sur "je n'arrive pas à me connecter" on déclenche un email. peut on mettre ce même texte en objet de ce mail? 

7/ j'ai trouvé à manquer la possibilité de me déconnecter sur mon mobile pour passer du compte demo à mon compte. Le log out sur mobile manque. On peut le rajouter dans la sidebar mais tout en bas?

8/ A reflechir : comment guider pour reinitialiser mot de passe. Pour l'instant email chez nous.

**Comment by savioarthu** [comment]
Petite précision pour le 2), les modifications sont effacées directement lorsqu'il quitte la session.

**Comment by mickael2407** [comment]
Pur le 3 je n'ai aucun moyens de basculer sur l'inscription.
A part le 2 tout est ok

**Comment by savioarthu** [comment]
Cool, je ne suppose que ce n'est pas déployé encore, tu attends que tout soit fini non ?

**Comment by savioarthu** [comment]
Ok vu
Je vais être chiant désoooolé !

1. ok 
2. vu ton message ok
3. pas possible ok
4.  Je sais que @lzpons l'a écrit comme ça mais ne pas oubliez les majuscules svp :
"creer un compte myBroodminder" --> Créer un compte MyBroodMinder
5. J'arrive pas sur l'onglet d'inscription mais connexion, mais est-ce possible techniquement ?
6. ok le mail mais attention au sujet : 'Problème de connexion' en français et connection en anglais.
7. ok  
8. ok
