### ISSUE TITLE
Augmenter les graphes de Raw Data

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#131]
Avec les ruchers complètement équipes comme celui de jbl on a du mal a regarder les courbes de température 
![Capture d’écran 2020-03-07 à 09 48 32](https://user-images.githubusercontent.com/41069288/76147739-a5720100-609f-11ea-9814-1be181de5c7b.png)

Proposition de prendre plus de place en agrandissant les graphes en hauteur
1/ metre le graph de température tout en haut et sur 50% de l'écran
2/ ensuite le poids sur l'autre 50% 
3/ puis en scrollant l'humidité (en dehors de l'écran, quand il y en a)
4/ ajouter un peu plus de marge supplémentaire à droite, on a du mal à naviger et très vite on tombe dans le graph et on zoome sans le vouloir

**Comment by mickael2407** [comment]
C'est en cours mais j'ai un problème concernant les zone  de couleurs j'y travaille

**Comment by lzpons** [comment]
vu

**Comment by savioarthu** [comment]
Je te laisse gérer cette issue @lzpons, je ne sais pas ce que tu veux exactement et si l'update correspond à ce que tu voulais

**Comment by lzpons** [comment]
vu, c'est ok !
