### ISSUE TITLE
Améliorations de l'Export excel 

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#132]
Je me suis servic de l'export excel cet après midi et voici ce qu'il m'a manqué.

1/ classer les capteurs dans l'ordre 41/42/43 dans les cases ui en ont plusieurs. Comme ça d'un coup d'oeil on voit les balances par exemple

2/ il y a qqch d'étrange sur les % de baterie. certaines cases on un format "xx %" et d'autres "xx%". Du coup excel ne comptend pas. On peut faire sans espace?

3/ remplacer le libelle de la colonne "NOTE" par "DERNIERE INSPECTION ANNOTEE"

Il faudrait ajouter une colonne avec la couleur de la reine. ça manque mais il y a un travail d'implementation à faire. donc on mettra le sujet dans une issue dédiée.

**Comment by savioarthu** [comment]
Good pour moi, sauf pour le pt3, j'ai toujours la colonne 'Note'.
<img width="1099" alt="Capture d’écran 2020-03-18 à 19 50 31" src="https://user-images.githubusercontent.com/49641714/76996428-cb29c080-6951-11ea-9fc9-195ba7a9f609.png">

**Comment by lzpons** [comment]
comme décrit tout en haut, les % c'est SANS espace et non avec. sinon excel (ou numbers) comprend rien

**Comment by mickael2407** [comment]
Fait problème de deploiement

**Comment by savioarthu** [comment]
D'accord, je validerai quand ça sera déployé car je ne vois aucun changement pour l'instant

**Comment by savioarthu** [comment]
Ok pour 1 et 3.

Pour 2, toujours des espaces à certains et d'autres non. Il faudrait donc enlever les espaces pour tout le monde dans la colonne battery mais aussi dans la colonne brood du coup.

<img width="252" alt="Capture d’écran 2020-03-20 à 18 18 47" src="https://user-images.githubusercontent.com/49641714/77189076-48cb0900-6ad7-11ea-9615-b7fc6689f034.png">

**Comment by mickael2407** [comment]
Moi dans mes test il n'y as pas d'espace dans brood

**Comment by savioarthu** [comment]
Effectivement quand j'exporte vers Excel, les % ont l'air aligné partout. 
@lzpons tu peux confirmer sur ton Excel à toi ?

**Comment by lzpons** [comment]
après vérif on voit que les cases avec une seule valeur prenent le chiffre numérique alors que les cases avec 2 valeurs considèrent du texte. D'ou les différences d'alignement.

Difficile d'identifier une solution qui convienne partout. On va vivre comme ça et voir à l'usage ce qui s'avère le plus utile.

![Capture d’écran 2020-03-24 à 14 35 53](https://user-images.githubusercontent.com/41069288/77432148-f858f180-6ddd-11ea-9a07-98625409f1e9.png)

**Comment by lzpons** [comment]
Je ferme et on y viendra lorsque nous aurons les idées plus claires.
