### ISSUE TITLE
Evolutions sur les calendriers

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#133]
1. Dans Explore, les cases violettes du jour n'appairaissent plus dans les calendriers à gauche et ceux à droite (uniquement quand pas de données météo), il faut les rétablir. 
<img width="1288" alt="Capture d’écran 2020-03-24 à 20 44 55" src="https://user-images.githubusercontent.com/49641714/77470054-5c94a900-6e10-11ea-9e7e-d64411dbc48b.png">

2. Les alertes de type 'Apiary' (loc:'Apiary') n'apparaissent pas dans le calendrier des ruches. Il faut que chaque alerte de rucher apparaissent dans le calendrier de toutes les ruches Tu pourras tester avec l'alerte de pluie (code 201) qui est présente sur plusieurs ruchers. 

3. (voir avec @lzpons  - en attente) 
Modifier les plages dans Explore et Apiary des calendriers. Tous ? Uniquement les alertes ? Rallonger les calendriers ou non ? Quelle plage ?

Le but est qu'à l'arrivée sur les différentes pages (le problème sera réglé en partie avec la nouvelle page matériel) dont notamment Explore, on puisse voir les alertes à venir et les prévisions à venir. 
Quelle plage ? 3J/5J ou 7J ?  A voir ce qui est les plus simple mais minimum 3 jours.

**Comment by savioarthu** [comment]
Après réunion, nous nous sommes donc accordés sur le point 3.
3. Il faut uniquement le calendrier des événements de MelliUx à J+3. (pour Apiary et Hive)

**Comment by savioarthu** [comment]
1. Ok vu. Attention il existe toujours un cas extrême quand pas de données météo, la case n'apparait pas : 
<img width="1572" alt="Capture d’écran 2020-03-30 à 20 42 39" src="https://user-images.githubusercontent.com/49641714/77949328-0bc8f880-72c7-11ea-933b-3aa0792dd6f8.png">

2. Je ne vois pas les alertes de ruchers dans les calendriers des ruches ? 

3. Ok, vu. Finalement tu as fait pour les 3 calendriers mais ça semble logique, c'est pas dérangeant comme ça.

**Comment by lzpons** [comment]
je ferme cette issue. Il reste uniquement le point n°2. à traiter:
**Les alertes de type 'Apiary' (loc:'Apiary') n'apparaissent pas dans le calendrier des ruches.**
mais je ne suis pas sur qu'il le faille car les alertes météo sont par définition éphémères. Il n'y a que l'alerte oxalique qui mériterait d'apparaitre. mais pour une seule on peut aller la chercher sur la vue rucher.
