### ISSUE TITLE
Les données horaires de certains capteurs ne s'affichent pas sur raw data

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#137]
L'interface Explore/Raw Data ne sait charger des données des capteurs T2 de type 47
Vérifier également qu'il sait charger des données des capteurs W de type 49

Pour vérifier, utiliser le 47:86:34

![Capture d’écran 2020-04-12 à 00 12 47](https://user-images.githubusercontent.com/41069288/79056019-58f78380-7c52-11ea-9020-06431d58d5e8.png)

**Comment by savioarthu** [comment]
Cela fonctionne, à la fois pour 47 et 49, partout.

**Comment by savioarthu** [comment]
Le problème est plus général. Je me suis aperçu que certains capteurs qui ont des références différentes des capteurs originaux (BC - AF, etc). Par exemple, A4:EE:F8 est un capteur de poids fonctionnel mais il n'apparait pas dans le graphique hourly.
Il faut modifier la fonction qui gère pour que ça s'affiche dans tous les cas pour tous les capteurs qu'on référence comme 'WEIGHT', 'T_HR' et 'T2' dans la collection Sensor.
