### ISSUE TITLE
Pouvoir desactiver le rucher Demo dans userprefs

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#139]
1. Permettre aux utilisateurs de masquer le rucher démo : ajouter l'option dans les userPrefs

2. Bloquer les modifs du rucher demo même en admin:
la faille décelée est que si quelqu’un a le mode admin (par exemple theo), change la photo du compte demo, ca va changer la photo du compte + pour lui mais pas pour les utilisateurs en partage. Par contre bouger les pastilles en admin devrait bouger pour tout le monde les pastilles.

3. Vérifier l'attribution du rucher démo à la création du compte. il semble qu'il y ait une anomalie avec des users qui en ont et d'autres qui n'en ont pas.

**Comment by InakiUrrutia** [comment]
Rucher demo deactivé pour tous les utilisateurs
