### ISSUE TITLE
Responsivité de la page Rucher avec la frange blanche verticale de droite

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#140]
Dans cette page on devrait pouvoir réduire la fenetre vers la gauche en consommant l'espace blanc disponible, sans que le reste ne bouge

![30_1_mellisphera](https://user-images.githubusercontent.com/41069288/79395263-88233300-7f79-11ea-8c21-56741c2be066.png)

Dans les faits ce qu'il se passe est que tout est réduit proportionnellement. Et qu'un écart entre graphiques s'installe (certes il disparait si on fait reload mais c'est pas le but.

![Capture d’écran 2020-04-16 à 00 31 56](https://user-images.githubusercontent.com/41069288/79395343-b143c380-7f79-11ea-9efa-57b0458d7d3e.png)
(cette photo est plus zommée que la précédente car les deux ont la même hauteur)

**Comment by lzpons** [comment]
Expected behavior on window resize
- collapse the white space on the right hand side before reducing size of other objects (calendars or pictures)
- the central calendar should move with the others, and not to shift w/r to them

![Capture d’écran 2020-06-29 à 00 30 02](https://user-images.githubusercontent.com/41069288/85959945-ed46cc00-b99f-11ea-907a-38353aa35c8d.png)

**Comment by kasuntech** [comment]
fixed and PR created
