### ISSUE TITLE
Explore/Données : l'affichage 1 jour et à 3 jours ne marche pas

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#145]
il affiche à la place 7 jours il me semble.

**Comment by lzpons** [comment]
When selecting 1 day or 3 days in the calendar presset (below the "Apply" button) the scale of the X axis graph does not update to that setting.
 
![Capture d’écran 2020-07-13 à 14 45 13](https://user-images.githubusercontent.com/41069288/87305917-8553c200-c517-11ea-8944-c5427f60a2e9.png)

**Comment by lzpons** [comment]
same issue on the calendar side, this time also with "1 month" displaying 5 week instead of 4 
2 month displays 9 week instead of 8 etc.

![Capture d’écran 2020-07-13 à 14 47 03](https://user-images.githubusercontent.com/41069288/87306059-c21fb900-c517-11ea-8860-1ad2935a35cb.png)

**Comment by lzpons** [comment]
Spec for calendar range display

- 1 day : today and yesterday / do not start on monday
- 3 day : today, yesterday and the day before / do not start on monday
- 1 day = 1 week (7 days+) start on monday
- 1 month = 4 weeks (28 days+) start on monday
- 2 month = 8 weeks (36 days+) start on monday
- 3,6,9 months => same thing with 28days+ x period
- 1 year = 365 days + start on monday

**Comment by lzpons** [comment]
Since (top left) date selector is shared among two spaces Hive/Brood and into Hive we always want to start from monday we need to see if we can make it different into "Brood" space without breaking too much things.

Check and confirm.

**Comment by kasuntech** [comment]
PR created

**Comment by lzpons** [comment]
ceci me semble soldé !
