### ISSUE TITLE
Display des calendriers avec 3 jours de forecast

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#148]
En ajoutant les 3j de forecast, es calendriers se marchent les uns sur les autres.

Pour le résoudre il faut juste enlever la semaine de trop en début de calendrier. 5 rangées maxi est suffisant. Ensuite on va dans Explore pour creuser plus loin

![Capture d’écran 2020-04-25 à 21 36 18](https://user-images.githubusercontent.com/41069288/80289137-0e3f3680-873d-11ea-8f3b-ae4259316c7e.png)

**Comment by lzpons** [comment]
Within MY APIARY space the calendars for Apiary (1) and Hive (3) should display a maximum of 35 days(5week) including the 3day forecast and always starting on monday

**Comment by kasuntech** [comment]
fixed in #140 fixing, PR created
