### ISSUE TITLE
Arbre du rucher se plie automatiquement à la 1ere selection

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#153]
idem que la #144 

Dans Explorer > Couvain je constate que lorsqu'on va selectionner la premiere ruche d'un rucher, l'arbre se plie intempestivement.

Faire ce test
1 déplier l'arbre
2 selectionner quelque ruche
3 déselectionner tout
4 reselectionner une ruche => ici l'arbre se plie sans raison !

Il ne faut pas que l'arbre se plie sauf si l'utilisateur le demande.

**Comment by kasuntech** [comment]
fixed and PR created

**Comment by lzpons** [comment]
Résolu dans  branche feature_fix avec PR de itsadeki
