### ISSUE TITLE
Pas de préférence pour choisir une station météo comme src de données

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#162]
Avant il était possible de choisir une station météo comme source de données. Depuis cette option a disparu. 
Cela doit être toujours implementé dans le code, mais il faut regarder pourquoi il ne s'affiche pas.

![Capture d’écran 2020-05-28 à 14 08 14](https://user-images.githubusercontent.com/41069288/83139691-0e8c7200-a0ed-11ea-900a-063803ba9c57.png)

**Comment by savioarthu** [comment]
Previmeteo a configurer dans les configs User, c'est ok, ça fonctionne.
