### ISSUE TITLE
Email notification when a hive reaches a specific weight

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#164]
_I just wanted to suggest a feature request. It would be nice if I could setup an email notification when a hive reaches a specific weight.  For instance, I know that when my Hive1 reaches 214 lbs, I need to add my next honey super.  So if I could set a weight alarm for 214 lbs on Hive1 and receive an email alert when that is reached, it would be awesome._

**Comment by lzpons** [comment]
suite à la discussion de ce matin.

**Comment by savioarthu** [comment]
L'utilisateur à l'origine de cette évolution a été prévenu. C'est fonctionnel de notre côté.
