### ISSUE TITLE
Warn: [DOM] Found 2 elements with non-unique id #message-text

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#167]
At login we find two different messages on the console
1. Solve this issue
![Capture d’écran 2020-06-07 à 16 04 58](https://user-images.githubusercontent.com/41069288/83970920-a3a31e00-a8d8-11ea-8a9b-2cc6172f5227.png)

2. Hide unnecessary printouts, maybe using a "debug" flag (into config.ts file?) to activate them 
![Capture d’écran 2020-06-07 à 16 06 29](https://user-images.githubusercontent.com/41069288/83970956-da793400-a8d8-11ea-8053-260ea7251be8.png)

**Comment by lzpons** [comment]
1. Appears to be solved
2. should use a debug flag (true / flase) on the config.ts file

**Comment by kasuntech** [comment]
new flag ((true / false) ) added to environment

**Comment by kasuntech** [comment]
fixed and PR created
