### ISSUE TITLE
Improvements to weather calendar

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#174]
It appears that the weather icons are used inversed to display weather conditions.

09d is small rain
![Capture d’écran 2020-07-21 à 13 16 33](https://user-images.githubusercontent.com/41069288/88048891-67f4a880-cb54-11ea-93a3-e2d1d2a0b7e6.png)

10d is higher rain 
![Capture d’écran 2020-07-21 à 13 16 43](https://user-images.githubusercontent.com/41069288/88048906-6fb44d00-cb54-11ea-9b65-92244f2e4e20.png)

However on the calendar charts we see that they are used inverse. But only with OpenWeatherMaps ?

This needs further investigation.

What has to be improved:
1. add "rain" quantity to the mail tool over the weather icon (under HRmin label)
![Capture d’écran 2020-07-21 à 13 31 12](https://user-images.githubusercontent.com/41069288/88050059-747a0080-cb56-11ea-899f-5390ee9f1f59.png)

2. replace rain icon with a drop instead of this cloud/snow/rain (path is already into the code, needs to uncomment)
![Capture d’écran 2020-07-21 à 13 32 51](https://user-images.githubusercontent.com/41069288/88050203-aee39d80-cb56-11ea-8f33-6785e18a4ed3.png)

3. check that the approrpriate icons are used depending on rain quantities
< 3mm/day => cloud / sun cloud / sun
> 3mm/day < 20mm/day => 9d icon grey cloud+1drop
> 20mm/day => 10d icon black cloud+3drop

**Comment by savioarthu** [comment]
3. ok
