### ISSUE TITLE
Ajouter une case à cocher "autoscale" dans Raw data

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#181]
Lorsqu'on analyse des mesures finement dans Explore > Data on aimerait avoir un axe Y dilatable pour bien regarder
Ce n'est pas le cas actuellement. Pour simplifier la vie on peut ajouter une case à cocher 

[x] autoscale Y axis

Par défut elle est décochée et les axes Y ont les valeurs min/max par défaut
lorsqu'on la coche on ajuste l'échèlle à ce qui est affiché 

Il s'appliquerait partout sur les 3 graphs à la fois.

![Capture d’écran 2020-10-31 à 10 57 50](https://user-images.githubusercontent.com/41069288/97776413-02a74f00-1b68-11eb-8ca5-f7ab6dad3a5a.png)

**Comment by InakiUrrutia** [comment]
Cf #189

**Comment by lzpons** [comment]
on peut zoomer
on aura l'échèlel auto lorsque valeurs négatives

on solde
