### ISSUE TITLE
Variable temperature scale on time series

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#189]
during winter below 0°C temperatures are not visible.
Need to set variable scale or let the user define own graph scale.

**Comment by InakiUrrutia** [comment]
Echelle adaptative en fonction de l'amplitude des valeurs, partant d'une echelle fixe standard
Implementer sur vue graphique unifiée

**Comment by lzpons** [comment]
échelles dynamiques à intégrer sur hourly pour la température uniquement.
vérifier avec Kristufek

**Comment by lzpons** [comment]
A tester

**Comment by lzpons** [comment]
ça marche
