### ISSUE TITLE
Au sign-up pouvoir choisir entre le wizard ou le rucher demo

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#19]
Actuellement lors du signup le rucher demo se charge mais le wizard est obligatoire. 
il faut un pop up qui permette à l'utilisateur de faire le choix entre l'un ou l'autre

**Comment by mickael2407** [comment]
Désactiver pour l'instant

**Comment by lzpons** [comment]
@mickael2407 on est d'accord que pour l'instant le wizard est débranché de partout nest ce pas?. On va fonctionner sans le wizard qui sera remplacé (avantageusement) par la vidéo quick start.

si c'est bien cela, tu peux fermer cette issue.

**Comment by savioarthu** [comment]
C'est bien désactivé.
