### ISSUE TITLE
Le curseur pointe la courbe selectionnée et pas toutes les courbes

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#191]
Bernat C propose d'améliorer l'affichage des courbes de couvain (et peut être des données hbh) en changeant le curseur pour qu'il affiche uniquement le label de la courbe survolée au lieu de tous les labels disponibles à la coordonné

![Capture d’écran 2021-03-09 à 22 37 10](https://user-images.githubusercontent.com/41069288/110541484-196a3d80-8128-11eb-9bd4-26cbde93de5b.png)

Faire la modif sur tous les graphiques x/y dans `Couvain` et dans `Données`

**Comment by lzpons** [comment]
@InakiUrrutia hésite pas à commenter sur l'issue lorsque la question est avancée de ton côté
avec Arthur on mettait l'issue en etat "To Check" avant de la clore

**Comment by InakiUrrutia** [comment]
Résolu.
