### ISSUE TITLE
Basculer Export excel vers inspections

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#196]
Il y a un petit souci ..

![Capture d’écran 2021-03-28 à 20 18 03](https://user-images.githubusercontent.com/41069288/112762957-b53de980-9002-11eb-9915-2aea0e618adf.png)

**Comment by lzpons** [comment]
Basculer les infos sur les inspections

![Capture d’écran 2021-07-22 à 12 17 21](https://user-images.githubusercontent.com/41069288/126624273-71a850dc-8087-4601-b730-3855f8f48dff.png)

**Comment by InakiUrrutia** [comment]
Résolu

**Comment by lzpons** [comment]
Reste enlever le bouton sur Mon Rucher

**Comment by lzpons** [comment]
fait
