### ISSUE TITLE
Afficher sur chaque ruche les notes du rucher

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#197]
Afficher les notes du rucher avec un picto différent : lève cadres ROUGE au lieu de jaune
Les montrer aussi sur le calendrier de chaque ruche (Explore > Hive) et sur le tableau dessous de l'image du rucher (peut être avec une ligne de couleur différente ex: fond gris clair?)

**Comment by InakiUrrutia** [comment]
Idem #150
