### ISSUE TITLE
Configuration barre principale

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#20]
~~1) Remplacer les anciens icônes web par les nouveaux~~
2) Supprimer le texte au survol
3) Ajouter un descriptif en dessous de chaque icône
a) Pour MelliUx : Mes Ruchers / My Apiaries
b) Pour Fleurs : Fleurs / Flowers
c) Pour MelliCharts : Analyse / Expert
d) Pour la partie contact tout en bas : Mon Avis / Feedback
e) Pour la config: Configuration Notifs / Notifs Settings
f) Pour la future FAQ : Support / Support
<img width="67" alt="Exemple" src="https://user-images.githubusercontent.com/49641714/68137937-0d64df00-ff28-11e9-9205-298e2592a7de.png">

**Comment by savioarthu** [comment]
Update

**Comment by savioarthu** [comment]
Nouvelle barre, un commentaire @lzpons ? Couleur ? Placement ? Taille texte ? Icônes ? etc.

<img width="95" alt="Nouvelle interface" src="https://user-images.githubusercontent.com/49641714/68775231-73d7b480-062e-11ea-86e8-f0b27a21f839.png">

**Comment by savioarthu** [comment]
1) Mettre à jour les logos d'alertes et de BroodMinder.

2) Réduire l'espacement entre les textes et les logos.

Voici les fichiers.
[NewIcon.zip](https://github.com/mellisphera/mellisphera-web/files/3880680/NewIcon.zip)

**Comment by savioarthu** [comment]
Parfait, mais de mon côté j'ai encore l'ancien icône d'alerte et non le nouveau ;)

**Comment by mickael2407** [comment]
J'ai mit la nouvelle
