### ISSUE TITLE
inspection du jour n'apparait pas sur calendrier

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#216]
ce calendrier devrait afficher le jour J, comme les autres calendriers le font aussi

![Capture d’écran 2021-06-20 à 16 56 21](https://user-images.githubusercontent.com/41069288/122678786-8772d600-d1e8-11eb-9f0d-91acc792761b.png)

**Comment by InakiUrrutia** [comment]
Résolu

**Comment by lzpons** [comment]
soldé
