### ISSUE TITLE
Paramètre couleur de la ruche

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#219]
Pour visualiser les données plus simplement pouvoir attribuer des couleurs aux ruches.
Certainement à partir du menu `...  > Edit Hive > Hive color` et proposer une palette de couleurs standard
Même chose pour les ruchers `...  > Edit Apiary > Apiary color` TBC

**Comment by InakiUrrutia** [comment]
Ajout de la configuration de la couleur des ruches a partir de "ooo" dans Explore

**Comment by lzpons** [comment]
Seulement sur Apiary, pour faire groupé
