### ISSUE TITLE
Préférences Utilisateur

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#22]
1)	Supprimer les 3 points de couleur dans le menu
<img width="155" alt="Couleurs" src="https://user-images.githubusercontent.com/49641714/68191854-b6efb300-ffb0-11e9-87ef-1cfb9157dc9f.png">

2)	Bouton Sauvegarder n’affiche aucun message de confirmation sur Safari, il faudrait !**

3)	Le bouton de choix de format marche très bien presque partout, attention juste dans l’ajout de Notes, le format ne change jamais (je ne sais pas si c’est possible techniquement de modifier cela). 
<img width="408" alt="Notes" src="https://user-images.githubusercontent.com/49641714/68191888-c242de80-ffb0-11e9-9929-357c8e980426.png">

4)	Quand on modifie le choix de format de date ou de systèmes unitaires, le bouton radio de l’autre menu saute (cf image)
<img width="163" alt="Radio" src="https://user-images.githubusercontent.com/49641714/68191908-ca9b1980-ffb0-11e9-9879-9c0c0896297d.png">

5)	Passage Métrique -> Impérial, ok ça se passe plutôt bien (il faut recharger la page pour que ça s’active par contre). Je note quelques soucis :
a.	En fait, ce sont les unités qui ne se chargent pas tout de suite et c’est pour ça qu’il faut rafraichir la page.
b.	 Le vent de la météo est en m/s alors qu’il devrait être en mph en EN et en km/h en FR (1m/s*2,276 = 1mph et 1m/s*3,6 = 1km/h).

6)	Pour la langue, impossible de savoir quelle langue je choisis, quand je clique sur un drapeau ça change la langue (bon ok on comprend quand ça traduit mais ce n’est pas très clair). Je pense qu’il faut partir du même principe avec un bouton radio pour chaque drapeau et un bouton sauvegarder (avec confirmation de la langue !). Il faut au moins une confirmation sur tous les navigateurs !** 

 Au niveau de la langue, voici les quelques soucis :
a.	Les menus de chaque Echart sont en Espagnol ??? 
<img width="149" alt="Espagnol" src="https://user-images.githubusercontent.com/49641714/68191956-df77ad00-ffb0-11e9-9b34-13de08658515.png">

b.	Les titres des graphiques dans Mesures de MelliCharts ne sont pas traduits. Idem dans Couvain (%), on veut Brood (%).

c.	Les descriptions/noms des alertes dans la page de config ne sont pas traduites.

d.	La page de listing des Ruchers dans le CRUD n’est pas traduite.
<img width="1605" alt="Ruchers_trad" src="https://user-images.githubusercontent.com/49641714/68191989-f0282300-ffb0-11e9-8816-0803b9df745b.png">

e. Si je me déconnecte et que je me reconnecte, le choix de la langue n’est pas conservé.
f.	Lorsque je passe de français à anglais et que je veux repasser à français, les pages restent en anglais (mise à part la page des préférences), impossible de changer la langue de nouveau.

7) Enfin, il faut supprimer le fait de pouvoir réinitialiser son mot de passer sur Mellisphera. Il faut donc centrer le fait de pouvoir créer un compte.

8) Pendant qu’on y est, classer par ordre alphabétique les ruchers et les ruches dans les différents listings

**Comment by mickael2407** [comment]
Le bug des préférences est corrigé, la trad les listings n'est pas faite étant donné que cette page est inaccessible depuis que j'ai masqué le menu

**Comment by savioarthu** [comment]
Ok tout est ok mis à part le problème avec Safari pour la validation de sauvegarde. 
Dernier détail, est-ce possible d'accorder la date de l'ajout de note avec le format des préférences ?
<img width="542" alt="Date des notes" src="https://user-images.githubusercontent.com/49641714/68754982-16c90800-0608-11ea-9a0e-20bffe2a1a08.png">

**Comment by savioarthu** [comment]
Il y ça aussi, quand on est en anglais ou en français, les unités entre parenthèses ne s'affichent pas dans les préférences. Elles sont affichées uniquement en espagnol. 
<img width="184" alt="Unités en espagnol" src="https://user-images.githubusercontent.com/49641714/70387128-7fa26680-19a1-11ea-8199-b77bf760aaba.png">

**Comment by savioarthu** [comment]
Fonctionne
