### ISSUE TITLE
Implementer les langues 

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#221]
- passer en mode drop down list, sans drapeaux
- ajouter lang par défaut = browser-default
- ajouter fichier de trad en roumain

[ro.json.zip](https://github.com/mellisphera/mellisphera-web/files/6860251/ro.json.zip)

**Comment by InakiUrrutia** [comment]
Traduction roumain ajouté et changements effectués dans parametres

**Comment by lzpons** [comment]
Reste à voir pour browser-default mais on ferme ce ticket.
