### ISSUE TITLE
weather : conversion unités

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#224]
pour le vent qui en base est en m/s
x3,6 pour passer en km/h
x2,237 pour passer en mph

Pour la température qui est en °C sur la base
 (T × 9/5) + 32 pour passer en F
 
Pour la pluie qui est en mm en base
diviser par 25.4 pour passer en inches 

Au passage dans `Explore > hive` il semble qu'il y ait aussi un pb de conversion d'unites sur le vent 
le 12/5/2021 @ 17h on a un max de vitesse à 8.05m/s 
- En METRIQUE sur le calendrier on voit bien 8.05x3,6 = 29km/h OK
- mais en IMPERIAL on trouve 16.1 mph alors que 8,05x2,237 = 18,007 => **on devrait trouver 18mph** 
![Capture d’écran 2021-08-31 à 11 25 45](https://user-images.githubusercontent.com/41069288/131478625-2cb0779d-88e3-4c22-af50-6fe8c3b1fa45.png)
==> Vérifier la conversion qui est réalisée par angular
==> Modifier la légende du calendrier de `Wind` à `Wind max.`

**Comment by InakiUrrutia** [comment]
La conversion a été réparée, il était écrit "2,237" au lieu de "2.237" ( il faut mettre un point pour les chiffres avec decimales )
Le calendrier de Explore > Wind affiche correctement la conversion
Elle est aussi appliquée sur les graphiques de Weather

**Comment by lzpons** [comment]
Il reste un petit loupé côté facteur mph

![Capture d’écran 2021-09-01 à 07 43 13](https://user-images.githubusercontent.com/41069288/131839889-1488c169-0637-4e38-b3a8-35657c07888b.png)

**Comment by SylvJalb** [comment]
Conversion réparé pour cas de l’arrondit également.
[Ici](https://github.com/mellisphera/mellisphera-web/commit/4642fdfe35092f42e9dff15acd3897477c4a0a73)
