### ISSUE TITLE
Bug Pastilles

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#23]
1) Premièrement après différentes analyses, j’ai remarqué que l’axe X-Y n’était pas comme on le pensait.
<img width="796" alt="PositionX_Y" src="https://user-images.githubusercontent.com/49641714/68195871-f66dcd80-ffb7-11e9-9651-bc41c308f768.png">

2) Un arrondi se fait sur toutes les ruches (Arrondi à l’unité inférieure) pour le positionnement des ruches (au changement de page ou à la déco)

<img width="300" alt="Deco:reco_arrondi" src="https://user-images.githubusercontent.com/49641714/68195888-01286280-ffb8-11e9-841d-192d71235b1f.png">

3) Gros décalage pour la dernière ruche du rucher dans la collection Mongo ! Toujours la même et toujours la dernière quel que soit le rucher. En fait il y a toujours l’arrondi sur X mais il y a un décalage de -10 à -12 (rien de régulier…) sur l’axe Y.

Exemple ici du problème:
J'ai mis R8 (dernière ruche de la liste sur mongo) au même positionnement que R2 pour comparer les positions.
<img width="300" alt="PlacementR2" src="https://user-images.githubusercontent.com/49641714/68196307-b0653980-ffb8-11e9-92b6-9795cdb4bede.png">
<img width="300" alt="PlacementR8surR2" src="https://user-images.githubusercontent.com/49641714/68196395-d7bc0680-ffb8-11e9-8c33-09d68e16e613.png">

On voit ici que tout se passe bien pour le moment, la nouvelle position est bien enregistrée. Je change de page et je reviens, la position reste la même sur mongo tandis que ma pastille s'est déplacée vers le haut et légèrement à gauche. 
<img width="114" alt="Déplacement pastille" src="https://user-images.githubusercontent.com/49641714/68196731-4c8f4080-ffb9-11e9-9f0b-9db3b3602141.png">

Sur mongo, j'ai pourtant la bonne position mais c'est un leurre. Quand je clique sur déplacer de nouveau sans bouger la pastille, la véritable position enregistrée s'affiche. 
<img width="300" alt="R8_new_position" src="https://user-images.githubusercontent.com/49641714/68196794-629d0100-ffb9-11e9-9c5f-824622627356.png">

On remarque donc cet arrondi à l'unité inférieure de 20.99 à 20 pour X (qui se voit légèrement car nous étions presque à l'unité supérieure) et ce saut de 44.875 à 33.085 pour Y (que je n'explique pas). 

Ainsi, ici nous devons:
1) Essayer de revoir le modèle d'arrondi. Soit le supprimer si c'est possible soit au moins arrondir à l'unité la plus proche (inférieur lorsque <0.5 et supérieur lorsque >=0.5).
2) Comprendre ce bug de la dernière ruche avec le saut de Y.
3) Et bien entendu supprimer ce saut lorsqu'on aura détecté le problème.

**Comment by lzpons** [comment]
il y a peut être un souci de déclaration de variable? il faut un long float?
une solution est de multiplier les coordonnées par 1000 ou 10000 et garder ainsi les derniers chiffres significatifs. On le fait souvent dans d'autres domaines en ingénierie.

**Comment by mickael2407** [comment]
J'ai beaucoup travaillé dessus mais reste un bug que je n'arrive pas encore à résoudre quand on change de page après avoir déplacé une ruche en revenant sur la page lorsque que l'on clique dessus elle remonte d'un crans, je cherche toujours

**Comment by lzpons** [comment]
Quelques conclusions intermédiaires après avoir regardé avec Mickael
- comme maintenant il force l'initialisation de translate(0,0) il n'y a plus de déplacement de pastille au retour sur la page.
- néanmoins le pb persiste lorsqu'on déverrouille. A l'instant où on vient effleurer la pastille pour le déplacer. hop! elle saute de -23px. Le translate s'est rempli tout seul on ne sait pas pourquoi.

Mongo suit tout le temps, sauf que sur Compass il faut le reveiller un peu (passer en mode table et revenir en mode normal par ex. recharge les données)
Il n'y a pas de souci d'arrondi car on cherche plusieurs unités dans l'affaire (2 en x et 23 en y)

**Comment by lzpons** [comment]
En l'état je pense qu'on peut se satisfaire de la solution que @mickael2407 a mis en place. Il reste un reliquat mais il faut passer en mode édition pour tomber dessus. On ferme
