### ISSUE TITLE
Inspections : on peut toujours enregistrer N fois

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#230]
Une fois saisie l'inspection, on devrait faire RAZ sur l'interface pour ne pas laisser l'impression que c'est pas enregistré.

**Comment by SylvJalb** [comment]
fait ! le formulaire se vide après la création des inspections

**Comment by lzpons** [comment]
ça marche, 
seulement lorsqu'il se vide le footer remonte au milieu de l'écran.

**Comment by lzpons** [comment]
La RAZ a bel et bien lieu maintenant
