### ISSUE TITLE
inspections : améliorations diverses

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#231]
1- activer par défaut (en base) tous les evenements toutes les saisons (et laisser l'utilisateur les desactiver)
 
2- Renomer en anglais
Buzzing hive => Laying workers
Mosaic brood => Scattered brood
Mite count lounge => Mite count sticky board

**Comment by SylvJalb** [comment]
![image](https://user-images.githubusercontent.com/44393569/133977465-42327404-7097-4b79-9830-50f479249fd5.png)
toutes les saisons sont activé par défaut (en base)

**Comment by SylvJalb** [comment]
Traduction anglaise corrigé [ici](https://github.com/mellisphera/mellisphera-web/commit/b3147beb3c0f382a06f6a9eb4786826270fbf497)

**Comment by lzpons** [comment]
Perfect !
