### ISSUE TITLE
Dans Weather pb affichage pour sources de type 58?

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#235]
Pb remonté par Dimae

![Capture d’écran 2021-09-07 à 17 38 53](https://user-images.githubusercontent.com/41069288/132373062-aac07a15-b68f-40e3-8e5d-1749d1383697.png)

**Comment by GrimSnake** [comment]
On donnait la _temp_int_ au graph alors que la balance remonte une _temp_ext_.
Corrigé dans [ce commit](https://github.com/mellisphera/mellisphera-web/commit/40da80a8ca78bf90c0349d48213623f78fb5213d)
