### ISSUE TITLE
Le bouton (?) dans Meteo > relevés pointe pas vers le chapitre associé

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#239]
En cliquant sur (?) on arrive dans 
https://doc.mellisphera.com/fr/mellisphera/

au lieu de dans 

https://doc.mellisphera.com/fr/mellisphera/#meteo_1

j'ai pas vérifié si c'est pareil en anglais

**Comment by SylvJalb** [comment]
corrigé avec le nouveau footer

**Comment by lzpons** [comment]
le lien pointe vers https://doc.mellisphera.com/fr/mellisphera/#releves
mais comme c'est la page d'accueil de l'onglet météo il devrait plutôt pointer vers https://doc.mellisphera.com/fr/mellisphera/#meteo_1

Au passage j'ai compris pourquoi il affiche cet "_1" dans l'url : c'est parce que il y a déjà un sous chapitre météo en amont du document, du coup même s'il n'est pas dans le même chapitre il met _1. Trop compliqué de changer sans avoir d'autres effets collatéraux.

**Comment by lzpons** [comment]
Résolu !
