### ISSUE TITLE
La Temp=0 sur module Weather avec source de type 43

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#251]
Sur le compte de RNOL on ne voit pas la température de la balance sur les courbes de weather.
Ceci permettrait de vérifier l'effet de l'exposition.
![Capture d’écran 2021-11-18 à 22 17 43](https://user-images.githubusercontent.com/41069288/142498179-181f5667-aa6d-4403-a8f1-4ff9eabdcc6e.png)

**Comment by SylvJalb** [comment]
![image](https://user-images.githubusercontent.com/44393569/146385027-77ec2c94-1aaf-4e0e-be17-f46dbacf5da4.png)
Je n'ai pas de temp=0 sur ce compte (RNOL), de mon côté ça à l'air bon.

**Comment by lzpons** [comment]
Résolu
