### ISSUE TITLE
#MelliCharts : Vent

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#28]
a. Ajouter la moyenne sur période et sur les 7 derniers jours.

<img width="376" alt="Pas de moyenne" src="https://user-images.githubusercontent.com/49641714/68372647-92771080-0141-11ea-8458-cb28873fef06.png">

b. Ajouter les Forecast comme sur les autres calendriers.

<img width="374" alt="Pas de Forecast" src="https://user-images.githubusercontent.com/49641714/68372623-89863f00-0141-11ea-949e-f22a761953c6.png">

**Comment by savioarthu** [comment]
Reste plus qu'à arrondir les moyennes et afficher la vraie valeur pour la période.
<img width="502" alt="Moyenne période" src="https://user-images.githubusercontent.com/49641714/68754856-d49fc680-0607-11ea-9e1f-876315665c04.png">

**Comment by savioarthu** [comment]
Arrondi ok 
Cependant, la moyenne sur la période déconne. Celle affichée ne correspond pas du tout aux valeurs. 
<img width="428" alt="Wind" src="https://user-images.githubusercontent.com/49641714/68847588-370fca00-06cf-11ea-8813-8f7e6e2079f2.png">

**Comment by mickael2407** [comment]
On peut créer un issues global pour les moyennes et les sommes

**Comment by savioarthu** [comment]
Ok les sommes ont déjà une issue et le reste est fait.
