### ISSUE TITLE
#MelliCharts : bug météo

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#29]
a. Il manque un accent sur le deuxième e de Méteo dans le titre. 

<img width="131" alt="Orthographe" src="https://user-images.githubusercontent.com/49641714/68372786-d407bb80-0141-11ea-8136-bc21c715ab00.png">

b. Renommer 'Pluie' en 'Précipitations'/'Precipitation' (EN)
<img width="170" alt="Renommer" src="https://user-images.githubusercontent.com/49641714/68756795-1716d280-060b-11ea-8c80-2e80ec6ae5a3.png">

c. [EDIT] Ne pas s'occuper de la neige à proprement parlé. Afficher juste un champ "Précipitations/Precipitation" avec la somme entre pluie et neige tombé la journée (en mm).

d. Retirer pour le champ 'Météo' les moyennes qui ne servent à rien ici.
<img width="387" alt="Moyenne" src="https://user-images.githubusercontent.com/49641714/68757135-b5a33380-060b-11ea-8888-be4af546e358.png">

e. Bug quand il y a conflit de sources. Typiquement, lorsque je suis sur un rucher qui n'a pas de données météo pour une source (BroodMinder la plupart du temps) sur la période choisie, une seule source s'affiche. 
Quand je change de période choisie, il y a conflit car il ne trouve pas l'autre source et la page charge indéfiniment. 

Voici le problème en image : 
1) Je suis sur mon rucher sur le derniers mois, je n'ai qu'une source : OWM
<img width="391" alt="OWM source 1" src="https://user-images.githubusercontent.com/49641714/68757167-c358b900-060b-11ea-81da-aa2ee4fd2f4d.png">
2) Je souhaite aller voir d'anciennes données, je change la période à 3 mois, tout se passe bien car pas de nouvelles données.
3) Je passe la période aux 6 derniers mois : chargement indéfini.

<img width="404" alt="Chargement indéfini" src="https://user-images.githubusercontent.com/49641714/68757304-0581fa80-060c-11ea-9674-b8e640205916.png">

L'erreur suivante s'affiche :
<img width="493" alt="Erreur" src="https://user-images.githubusercontent.com/49641714/68757347-1599da00-060c-11ea-9f21-87c016498f28.png">

Pour moi l'erreur est claire, on a une source et cela va passer à deux sources avec l'ajout de BroodMinder. Cependant, il ne trouve pas le nom de la série car elle n'était pas là au chargement des anciennes périodes.

**Comment by savioarthu** [comment]
Mise à jour

**Comment by mickael2407** [comment]
Mettre la neige dans le calendrier météo (global) ne serais pas plus judicieux ce n"est pas un paramètre très important

**Comment by savioarthu** [comment]
En effet, j'ai édité le point c.
A vrai dire la neige en elle-même ne nous intéresse pas. Mais ce serait bête de prendre en considération que la pluie et pas la neige. Pour moi, il faut regrouper les deux sans distinguer que ce soit de la neige ou de la pluie. Ce n'est donc qu'une somme journalière de la pluie et de la neige. 


c. [EDIT] Ne pas s'occuper de la neige à proprement parlé. Afficher juste un champ "Précipitations/Precipitation" avec la somme entre pluie et neige tombée la journée (en mm).

**Comment by mickael2407** [comment]
Résolu pour les somme voir l'issue dédié

**Comment by savioarthu** [comment]
Ok pour les sommes, c'est déjà dans une autre issue.
Par contre, je ne suis pas sur qu'au survol des précipitations, tu prennes en compte la neige ? 
Elle est toujours à 0 dans tous les cas, peut-être un manque de chance, j'attends ta confirmation avant de fermer l'issue.

**Comment by mickael2407** [comment]
La neige est bien présente 
![Capture d’écran de 2019-11-27 11-50-24](https://user-images.githubusercontent.com/37872697/69717620-adb7b900-110c-11ea-844e-8f1268a3ff29.png)

**Comment by savioarthu** [comment]
Parfait, je ferme.
