### ISSUE TITLE
#MelliCharts : Calcul des moyennes/sommes

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#30]
Ruches : Calcul des moyennes
a. PREMIER calendrier : il ne fonctionne pas totalement. Quand je passe du couvain au poids de la ruche, il garde l’unité et la valeur du niveau de couvain, etc. Quand je change de ruche, il y a également un problème de calcul. (Attention, ces problèmes ne se passent pas tout le temps).
En voici un example avec la ruche RHH de LPO :

<img width="391" alt="Problème Somme" src="https://user-images.githubusercontent.com/49641714/68373759-d0753400-0143-11ea-8059-be20197ccc42.png">

b. TROISIEME calendrier : Pour le vent, il faut rajouter la somme sur la période et sur les 7 derniers jours.

<img width="393" alt="Vent" src="https://user-images.githubusercontent.com/49641714/68373648-999f1e00-0143-11ea-94c2-69980e9491f5.png">

c. Toujours sur le 3ème : il faudrait enlever le calcul de ces moyennes lorsqu’on arrive sur Calendrier Lunaire. Si cela est envisageable. 

<img width="390" alt="Calendrier Lunaire" src="https://user-images.githubusercontent.com/49641714/68373613-88eea800-0143-11ea-8f50-c21121f6c2a5.png">

d. Toujours sur le 3ème : Ne calcule pas la somme de pluie sur les 7 derniers jours.

<img width="397" alt="Somme pluie" src="https://user-images.githubusercontent.com/49641714/68373573-7b392280-0143-11ea-8f61-d2c010cc81dc.png">

e.En termes de détails, il faut espacer (en FR) les « : » des textes.

<img width="362" alt="Espacement : " src="https://user-images.githubusercontent.com/49641714/68373518-6066ae00-0143-11ea-8e5a-4cc0c2156f91.png">

**Comment by mickael2407** [comment]
Réglé il reste le problème du poids ou çà garde l'unité du couvains, je n'ai pas encore trouvé

**Comment by savioarthu** [comment]
Les sommes pour la pluie ne prennent pas en considération la neige, il faut faire la somme entre pluie et neige dans le calcule de la somme.

<img width="406" alt="Neige" src="https://user-images.githubusercontent.com/49641714/69899534-fcad5a80-1367-11ea-9b5d-3a1199e04359.png">

**Comment by lzpons** [comment]
Vu avec Mickael, on va procéder de la façon suivante.
1/ enlever la ligne qui concerne les 7 derniers jours et qui complique le code pour rien
2/ Garder la ligne des moyennes sur la période

Quelque chose comme cela
*Sur la période sélectionnée : *
     maximum jour :  +1.7 kg
     minimum jour :  -1.2 kg
     moyenne période : 0.5 kg
     somme période : 20.2 kg     (pour les poids uniquement)

**Comment by lzpons** [comment]
on ferme et on rouvrira sur Material avec une spec plus précise.
