### ISSUE TITLE
#MelliUx : Taille et placement du calendrier des événements

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#34]
Problème de taille des icônes sur le calendrier.

<img width="684" alt="Taille icône" src="https://user-images.githubusercontent.com/49641714/68378287-2352e980-014c-11ea-8fc1-818295eaa5cf.png">

Il faut peut-être l’agrandir en diminuant la taille de la bande noire, en montant un peu le titre et en baissant un peu les 2 autres calendriers comme on peut le voir ci-dessous.

<img width="795" alt="Idée d'amélioration" src="https://user-images.githubusercontent.com/49641714/68378367-4382a880-014c-11ea-901e-b1db8bf80e36.png">

Ou même peut-être diminuer la taille des cases des calendriers en dessous pour pouvoir afficher plus grand le calendrier des notifications, **il faut absolument tester des choses pour avoir les icônes dans les cases.**

**Comment by lzpons** [comment]
Je propose de retourner les calendriers à la verticale et ne montrer que les dernières 4 semaines.
Ca va élargir les cases et laisser de la place pour les pictos.
On sera également en accord avec mellicharts : même formatage.
Qu'en dites vous? on tester pour voir comment cela rend?

**Comment by mickael2407** [comment]
Mis à la vertical an attente de validation

**Comment by savioarthu** [comment]
J'aime bien et les icônes rentrent enfin dans les cases (sur ordi en tout cas).
Peut-etre rapprocher les calendrier par contre ? Ils m'ont lair trop espacés.

**Comment by savioarthu** [comment]
Et la semaine supplémentaire sur le calendrier des ruches ne sera jamais utilisé/rempli (pour couvain et poids et pour le calendrier tant qu'on aura pas rassemblé les événements ruchers et ruches sur un même événement).

**Comment by lzpons** [comment]
effectivement, ce vendredi en fin de journée on a décidé avec Mickael de figer les dimensions des écrans (puisque la cellule du calendrier est figée tout ce qui remonte jusqu’à la page est un peu contraint.

du coup on va définir trois affichages type (écran, ipad, smartphone) et définir des tailles associées.
De cette façon la distribution sera globalement figée et bien aménagée.
lrosqu’on va retraicir l’affichage des scroll apparaitront mais c’est mieux que des graphes qui se chevauchent

**Comment by savioarthu** [comment]
@lzpons A toi de voir ci cela convient à tes exigences.
De mon côté je valide sur iphone. 
Reste à voir tablette et ordi pour toi.

**Comment by lzpons** [comment]
On a beaucoup avancé sur ce sujet 👍 . S'il y a d'autres ajustements ce sera à la marge ou dans un contexte différent.
Je ferme
