### ISSUE TITLE
#MelliUx : Notifications/Inspections 

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#35]
1) Même chose que pour MelliCharts --> quand plusieurs observations il faut afficher  l'icône d'inspection sur le calendrier et non "..."

2) De même, faire en sorte que les messages ne sortent pas de l’écran.

<img width="735" alt="Taille messages" src="https://user-images.githubusercontent.com/49641714/68378602-ad02b700-014c-11ea-823d-979802ebce1d.png">

3) Si je désactive les notifications, les notifications présentent dans ‘… ‘ ne s’effacent pas et inversement pour les inspections. 
 
<img width="624" alt="Effacement" src="https://user-images.githubusercontent.com/49641714/68378615-b2600180-014c-11ea-950b-e52f0d947961.png">

**Comment by savioarthu** [comment]
Toujours le même soucis de mon côté quand je décoche l'un ou l'autre. 
<img width="735" alt="Problème" src="https://user-images.githubusercontent.com/49641714/69168674-6a9b8b80-0af7-11ea-970f-3a4553ac97b0.png">

**Comment by savioarthu** [comment]
Ca fonctionne de ton côté ? Car moi toujours pas, peut-être pas encore push ?

**Comment by savioarthu** [comment]
Ca fonctionne de ton côté ? Car moi toujours pas, peut-être pas encore push ?

**Comment by mickael2407** [comment]
Il me semblait avoir convenu avec @lzpons que pour l'instant on laissé la sélection des séries comme ça ?

**Comment by lzpons** [comment]
de ce que j'en comprends, actuellement si on déselectionne une série, les '...' ne vont pas se remplacer par le picto restant (unique). Il est vrai que ce serait mieux de recalculer et afficher seulement ce qui reste.
il est vrai aussi que pour l'instant cette issue est mineure. on laisse ouvert et on y reviendra plus tard.

**Comment by lzpons** [comment]
on oublie pour l'instant
