### ISSUE TITLE
# MelliCharts : Calendrier poids maximum

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#37]
Actuellement le calendrier de poids max ressemble à cela.

<img width="384" alt="Poids Max " src="https://user-images.githubusercontent.com/49641714/68379684-a412e500-014e-11ea-8978-5c9bb0b8358a.png">

On sera tous d'accord pour dire que c'est moche et que n'a aucune utilité à l'heure actuelle puisque tout est figé. 

Premières questions :
1) Comment afficher le poids maximum de la meilleure façon ? 
2) Si l'on souhaite rester sur l'affichage actuel : 
a. Quelle formule prendre pour les cercles ? 
b. Comment rendre plus attrayant le calendrier ? Possibilité de changer la couleur (le vert flash sur toutes les cases ébloui légèrement) ? Degré de couleur ? 
3) Est-ce plus judicieux de changer l'affichage actuel ?

**Comment by lzpons** [comment]
pas facile car le poids peut changer de 20 à 150kg sur la saison et de 100gr à quelque kg chaque jour. Donc on a a faire à une plage de valeurs trop large avec une résolution très fine. Pour ça les bulles ne sont pas nécessairement les plus adaptés. Peut être le mieux est d'afficher les valeurs avec du texte comme dans cet exemple :
https://echarts.apache.org/examples/en/editor.html?c=calendar-lunar

Chaque jour on affiche le poids absolu avec 2 chiffres sign après la virgule "33,25kg 15.25lb"

**Comment by savioarthu** [comment]
Finalement, on le remplacera par Fitness, une issue est déjà créée, je ferme celle-là. 
Issue #111
