### ISSUE TITLE
la pastille ne repond pas à la souris. il faut cliquer le label

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#42]
Description :
Impossible de sélectionner une ruche en cliquant sur la pastille. Il n'y a que le label qui permet d'activer la ruche.

Objectif :
Remettre la possibilité de sélectionner la ruche en cliquant sur la pastille.

**Comment by mickael2407** [comment]
Mettre clique sur la pastille provoque un conflit avec le drag and drop c'est pour cela que l'on avais mis un double clique sur la v1

**Comment by savioarthu** [comment]
Simple clique pas possible techniquement mais double clique marche toujours.

**Comment by lzpons** [comment]
avec @mickael2407 on a choisi de mettre une condition : 
- si cadenas fermé => simple clic affiche la ruche
- si cadenas ouvert => simple clic déplace

puis sur le format de la pastille
- sélectionner = pastille avec bord magenta continu
- déplacer = pastilles avec bord noir pointillé

**Comment by savioarthu** [comment]
C'est ce que je vois ;)
