### ISSUE TITLE
Traduction interface en espagnol

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#44]
@mickael2407 comment faut-il faire pour traduire l'application en espagnol?
Je sais qu'il y a un json quelque part dans la structure du code
Dis moi où il se trouve et je m'en occupe.

**Comment by mickael2407** [comment]
Il y a les json ici https://github.com/mellisphera/mellihealth-web/tree/master/src/assets/i18n

**Comment by mickael2407** [comment]
Il manque la traduction des alerts

**Comment by savioarthu** [comment]
Traduction sur Git 
Idem pour la lune, je pense que tu devrais prendre le json et adapter en fonction de la langue choisi, et non que ça soit dans mongo. Pour l'instant, on laisse telle que c'est, on en discutera quand je reviendrai, ça sera plus simple. 

Lien Moon : https://github.com/mellisphera/StackData/tree/master/DailyRecords -> Moon.json
Lien Alertes : https://github.com/mellisphera/StackData -> codeAlert.json

**Comment by lzpons** [comment]
c'est fini.
