### ISSUE TITLE
Gestion des sources météo 

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#45]
Il faut qu'on puisse gérer les différentes sources de Météo : BroodMinder, Previmeteo, OpenWeatherMap. 
Actuellement on les gère de telle façon qu'on choisit sa série sur les calendriers (temps et pluie uniquement pour l'instant). 
<img width="372" alt="Choix" src="https://user-images.githubusercontent.com/49641714/68755829-60662280-0609-11ea-8746-85bfba1a61af.png">

Nous sommes aujourd'hui limités puisque le choix n'est pas possible sur tous les calendriers. De même chaque calendrier possède ses propres séries et l'utilisateur doit cocher à chaque fois celle qu'il souhaite, ce n'est pas optimal. 
Il faut donc lui laisser le choix de pouvoir sélectionner par défaut une source. Chaque utilisateur a deux sources différentes : OpenWeatherMap (à condition d'avoir un rucher valide dans la base, i.e avec un codePostal et un codePays valides) et BroodMinder (à condition d'avoir des données sur son rucher). Lorenzo a en plus sa propre station Previmeteo. 

La question ici est de savoir où l'utilisateur doit choisir sa source ? Directement sur Mellicharts à un endroit approprié ou dans les préférences ? A un autre endroit ?

**Comment by lzpons** [comment]
Comme discute tout à l’heure, on mettra la sélection dans les préférences et on ajoutera un texte sous le calendrier qui indique la source 
Ex : 
Source : weathersource.com
Source : weatherstation
Source : openweathermaps

**Comment by savioarthu** [comment]
Ok, il reste Previmeteo pour lpo et ça sera ok.
