### ISSUE TITLE
Preferences utilisateur plus simple

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#46]
Je note que les boutons radio dansent encore quand on les bouge sans sauvegarder successivement. Comme proposé par @mickael2407, pour faire plus simple enlever les boutons "sauvegarder" et enregistrer les choix par défaut à la fermeture de la fenêtre 

Au même temps le texte est collé aux boutons radio

Implémenter 
- ajouter un bouton "Sauver et Fermer" qui enregistrera au même temps
- aérer l'espace entre le bouton radio et le texte associé 
- mettre les unités entre parenthèses 
-- "Métrique (°C, kg, m)"
-- "Imperial" (F, lb, f)"

**Comment by mickael2407** [comment]
Bon j'ai enlevé les boutons la sauvegarde se fait à chaque changement

**Comment by savioarthu** [comment]
De mon côté, je ne vois pas les changements effectifs demandés par Lorenzo, j'ai pourtant vidé le cache à plusieurs reprises. 

Manque:
-Espacement
-Unités entre parenthèses,
-Gestion sauvegarde

Dernière chose, traduire Langue en Language quand on passe de FR à EN.
