### ISSUE TITLE
Améliorer le rendu dans MelliCharts

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#47]
Plusieurs améliorations esthétiques pour que ce soit plus cool à naviguer
- ruchers par ordre alphabétique (il dot y avoir une issue dédiée)
- rucher par défaut le premier, toujours déplié (un jour dans les user prefs on permettra de choisir le rucher par défaut qu'on veut afficher)
- taille du cadran de la date un peu plus large pour laisser la place
- changer les pictos de l'arbre 
- espacer gain/loss de l'ID du capteur dans productivité
- espacer les deux lignes de texte sous le graphe
- centrer le logo sur la sidebar
- changer les pictos ruche/rucher par les nouveaux pictos sans abeilles (plus clean)

Remarquer aussi que sur ipad les pictos prennent 2 lignes sauf pour les events: du coup les calendriers ne sont plus alignés. Je ne sais pas s'il y a une solution à cela...

Tous les points sauf le dernier sont détaillés dans le gribouillage ci dessous
![Capture d’écran   2019-11-14 à 23 42 42](https://user-images.githubusercontent.com/41069288/68995015-68cc9080-0889-11ea-9175-a1d688dcffba.png)

**Comment by mickael2407** [comment]
Les ruchers sont déjà trié par ordre alphabétique

**Comment by lzpons** [comment]
Tout semble soldé sauf l'espacement sur les moyennes.
Je clôture ce ticket et vais en ouvrir un nouveau avec d'autres éléments nouveaux.
