### ISSUE TITLE
Meilleure identification du device avec batterie faible

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#48]
Souvent sur une ruche on a deux ou trois capteurs. Les alertes nous disent lequel a une batterie faible mais il faut survoler la notif pour trouver son ID et savoir si c'est la balance, le T2 ou le TH.

Imaginer des pictos qui porteraient l'information, soit parce qu'on appose T2, TH, W.. à l’icône, soit parce qu'on a des pictos représentatifs du device carrément.

Prio 2 pour l'instant mais à garder dans le backlog.

**Comment by savioarthu** [comment]
Cf -> Gestion des alertes associées aux capteurs mellisphera/StackData Issue #12

**Comment by savioarthu** [comment]
Je ferme, on centralise sur #69
