### ISSUE TITLE
Trouver une loi asymptotique pour la pluie

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#52]
Parfois lorsqu'il pleut beaucoup les goutes sont vraiment grosses sur le calendrier.
comme ici chez Dominique. 

<img width="430" alt="Capture d’écran 2019-11-17 à 14 40 23" src="https://user-images.githubusercontent.com/41069288/69014374-e081e480-0989-11ea-9bd1-31e8ea4f2890.png">

Une loi cubique qui démarre rapidement et qui devient asymptotique à partir d'une bonne pluie chargée serait idéale pour répondre à cette problématique. De toute façon lorsqu'il pleut des cordes on ne se demande plus si c’était beaucoup ou beaucoup beaucoup.

Je vous laisse la trouver ;) !

**Comment by savioarthu** [comment]
Une formule basique, je sais pas si elle est très compréhensible 👍 
tailleGoutte = minutes(3/2*pluie, tailleMaxCase)%
avec :
tailleMaxCase = 100%
tailleCase = taille de la case le jour concerné
pluie = pluie tombée en mm le jour concerné

En gros on prend le minimum entre 2 fois la pluie du jour et la taille maximum de la case (taille logique pour que la goutte soit lisible). 

Exemple :
La taille maximale d'une case correspond à 100% de possibilité de remplir la case.
Si aujourd'hui il a plu 20mm, minimum(3/2*20,100) = minimum(30,100) = 30.
Ainsi la taille de la goutte sera de 30% de la taille maximale pour un jour où il pleut 20mm.
Pour 30mm cela sera 45%, 40mm 60%, 50mm 75%, 60mm 90%, 66,6mm correspondra à 100% et au delà la goutte sera toujours à son maximum et donc de la même taille. 

La formule est-elle claire ?

**Comment by savioarthu** [comment]
[EDIT]
J'ai ajusté la formule car j'ai remarqué qu'il pleuvait très souvent moins de 30mm et que le reste restait exceptionnel, il fallait donc trouver une formule plus adéquate pour pouvoir voir une différence notable entre 0 et 30mm. Au dessus, on s'en fiche, la gouttera sera à son maximum à partir de 33.33mm.

**Comment by lzpons** [comment]
de mon côté, en partant de la proposition de @savioarthu, je propose une loi "pluie ~surface de la goutte" dans la même logique que pour la productivité.

On aurait une loi en racine TailleGoutte = k*Racine(pluie)
elle n'est pas asymptotique mais y tend et en plus démarre très vite.
ici k=12

![image](https://user-images.githubusercontent.com/41069288/69227326-efcb8280-0b81-11ea-8790-a561912e815f.png)

**Comment by mickael2407** [comment]
J'ai essaye la formule plus haut mais cela dépasse des case. 
La formule va t'elle changé suivant qu'on sois en métrique ou en impérial

**Comment by savioarthu** [comment]
La formule de lorenzo ? 
Il faut limiter à 100 la valeur maximale. Si val > 100, val = 100. Ça doit rentrer dans la case avec sa formule.
En ce qui concerne impérial/métrique, la formule est à adapter car 1 inch = 25,4mm.

**Comment by savioarthu** [comment]
La formule fonctionne correctement en Métrique.
1) En impérial, j'ai toujours le même soucis qu'avant:
<img width="434" alt="Probleme impérial" src="https://user-images.githubusercontent.com/49641714/69899516-b35d0b00-1367-11ea-8302-deac76fdbe6a.png">
Il faut donc adapter la formule en impérial en sachant que 1 inch = 25,4mm.

2) En suite, la goutte n'augmente que si j'augmente la pluie. La neige est pas prise en compte dans le calcul. Il faut faire la somme pluie+neige dans la formule et non prendre que la pluie.
<img width="406" alt="Neige" src="https://user-images.githubusercontent.com/49641714/69899529-e56e6d00-1367-11ea-9abe-f6a9e1da431d.png">

**Comment by mickael2407** [comment]
Vérifié en métrique & en impérial c'est ok

**Comment by savioarthu** [comment]
De mon côté, c'est toujours pas ok en impérial.
<img width="417" alt="Problème taille impérial" src="https://user-images.githubusercontent.com/49641714/69973867-7c802400-1524-11ea-96fd-9cc92fc9a2ea.png">

Ensuite, toujours les soucis de que je mets uniquement de la neige, aucun icône s'affiche, il faut faire somme pluie + neige. 
Et dernier détail que je n'avais pas vu, en impérial la neige n'est pas converti en inches, elle reste en mm, c'est problématique.
<img width="374" alt="Neige impérial" src="https://user-images.githubusercontent.com/49641714/69974021-c2d58300-1524-11ea-83f0-b7b0cace03c3.png">

**Comment by mickael2407** [comment]
Chez moi en impérial :
![screen](https://user-images.githubusercontent.com/37872697/69975728-01b90800-1528-11ea-9e76-b625b71df6db.png)

**Comment by savioarthu** [comment]
Parce que tu testes sur une valeur toute petite, j'ai testé dans le cas d'un jour où il pleut beaucoup.

**Comment by mickael2407** [comment]
C'est quelle rucher ?

**Comment by savioarthu** [comment]
Ok tout est bon de mon côté, sauf une dernière chose. Quand je mets un très grande valeur en **impérial** (par exemple 1000mm) que ce soit pour la pluie ou la neige, l'icône devient énorme. On est d'accord que ce genre de valeur n'arrive jamais mais il faut tout de même que ça marche dans tous les cas.

Encore un petit effort, c'est presque bon !!

PS : Je te laisse la valeur extrême pour que tu voies et que tu saches quand c'est ok de ton côté, je l'enlèverai par la suite. 

**Rucher : 'GUINDALOS' le 2 décembre 2019**

<img width="550" alt="Imperial bug " src="https://user-images.githubusercontent.com/49641714/70086070-df031e00-1611-11ea-9fad-acb4a51fa3b8.png">

**Comment by savioarthu** [comment]
C'est bon !
