### ISSUE TITLE
Pouvoir cliquer sur la pastille pour visualiser les données de la ruche

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#53]
Je ne sais plus la raison pourquoi on a désactivé cette fonction (qui marchait avant). Mais le fait est que les utilisateurs viennent cliquer dessus sans qu'il ne se passe rien. Parfois ils finissent par penser qu'il faut double cliquer... 

Il faut trouver une solution pour permettre au geste le plus intuitif de dérouler la suite logique.

**Comment by mickael2407** [comment]
Fait on peut cliquer quand les ruches sont verrouillés
