### ISSUE TITLE
Améliorations d'UX dans Mellicharts

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#54]
Après une discussion avec Dominique, voici une liste de "petits" détails qu'on devrait prendre le temps de discuter ensemble pour améliorer l'UX de l'interface

- indiquer la légende sur le picto pour que ce soit plus rapide d'accès (humidité, température, poids)
- remplacer "poids maximum" par "poids total"
- remplacer "humidité" par "humidité externe" pour être cohérent avec le reste
- productivité : les utilisateurs ne savent pas de quoi il s'agit, ou en tirent des suppositions incorrectes. Il faut qu'on mette une pastille (i) pour indiquer comment chaque champ est calculé. Peut être à côté ou en dessous du calendrier. A voir.
- expliquer également es sources météo (d'où ça vient et ce que ça fait) : la plutot qu'un (i) c'est vers la FAQ qu'il faudrait diriger?
- pareil pour essaimage : quels sont les critères? il me faut un ou deux capteurs? quand est-ce que ça saute? => (i) + FAQ?
- Une proposition pour la météo de garder un seul picto HR, TEX et d'afficher les max/min au survol. Cela ferait plus simple et  à l'usage on a les deux infos d'un seul coup. Par contre que faut-il afficher? la moyenne?

EVENEMENTS
- mettre le calendrier lunaire avec les événements. c'est plus logique !
- de cette façon on pourra activer les différentes icones sur événnements. Actuellement elles sont figées et les utilisateurs cliquent dessus sans résultat
- sur les pictos de notif (sidebar/mellicharts) enlever la pastille rouge : intuitivement les utilisateurs penseront qu'ils ont une notification, alors qu'il n'en est rien.

**Comment by savioarthu** [comment]
Pas de moyenne dans la météo, je pourrais le rajouter s'il faut.

Pour les essaimages, il faut un capteur T et un capteur W sur une même ruche. Les détails de l'algorithme après sont très précis et non pas besoin de connaitre les détails à mon avis.

**Comment by savioarthu** [comment]
Beaucoup de choses faites et le reste (informations (i) sont dans une autre issue). On ferme ?
