### ISSUE TITLE
Transiter le token sur plusieurs onglets

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#55]
actuellement le token de login est restreint à l'onglet en cours, ors parfois on veut ouvrir une nouvelle page à côté pour comparer. Il faut de nouveau se connecter.

Implémenter la possibilité de transiter sur plusieurs onglets sans accrocs.

**Comment by lzpons** [comment]
Je rouvre le ticket car je constate que ça ne marche pas chez moi.
voici ce que je fais : j'ai un écran ouvert puis je vais sur la sidebar et clique bouton droit sur un des pictos pour ouvrir la page sur un autre onglet. La page s'ouvre avec l'écran de login.
sur chrome : OK
sur Firefox : KO

**Comment by mickael2407** [comment]
Vérifier sur firefox et sur chrome ca fonctionne !!

**Comment by savioarthu** [comment]
C'est bon pour moi aussi (Safari également).
