### ISSUE TITLE
Améliorations sur les alertes

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#56]
Intégrer dans la mesure du possible les remarques de Theo dans l'image ci dessous.
pour les champs qui n'ont pas de "ruler" voir s'il le faut ou pas. je n'ai pas creusé de ce côté.

Par ailleurs, à mon gout il faut figer une largeur maxi de page. Sur un grand écran tout est trop éparpillé. Tout a droite il faut une marge sinon les boutons sont collés au bord.

Je vois également que la position des curseurs n'est pas en accord avec la valeur affichée. Lorsqu'on les déplace on s'en rend vite compte.

![Screen Shot 2019-11-21 at 07 42 22](https://user-images.githubusercontent.com/41069288/69356192-571d2b80-0c83-11ea-9ddc-93595b1af823.png)

**Comment by savioarthu** [comment]
Il faut aussi que je m'y colle pour modifier le fonctionnement de certaines alertes. Sûrement demain mais plutôt dimanche, j'aurais pas le temps avant je pense.
Pour compléter:
Tmin entre 25°F et 50°F (-3°C et 10°C) -> de base 40°F et 5°C
Tmax entre 95°F  et 110°F (35°C et 43°C) -> de base 100°F et 38°C.
LowBrood entre 10 et 50% -> de base à 20% et PRECISER dans la description que l'alerte ne saute qu'au printemps/été
LowBattery entre 10 et 50% -> de base 20%
ColdPeriod -> PRECISER dans la description que cette alerte ne fonctionne qu'au printemps /été.
Cette alerte est pour moi NON PARAMETRABLE puisqu'elle détecte une période de froid par rapport aux normales de saison en fonction des mois de l'année. Son fonctionnement actuel ne permet en tout cas pas la mise en place d'un seuil.
Stolen hive -> Actuellement, nous avons deux critères pour cette alerte. Le premier est un delta de poids entre deux heures, le second est le poids total de la ruche. Si l'on combien un poids total < seuil défini et un delta < seuil défini, l'alerte saute. Le delta est fixé à 10kg et on peut rendre le poids modifiable, cela correspondrait au poids d'une ruche vide au maximum. 
Ainsi on peut dire que Stolen Hive entre 10lb et 40lb (5kg et 20kg) et de base 20lb/10kg.

**Comment by savioarthu** [comment]
Pour t'aider un peu et éviter que ça te prenne trop de temps @mickael2407 , j'ai :
-Mis à jour dans mongo les noms demandés par Théo
-Mis à jour dans mongo les step/nouvelles valeurs et range de ce que j'ai dit précédemment. 

Il te reste donc à faire :
-Renommer la page 
-Mettre les boutons On/Off partout (finalement)
-Mettre toutes les barres de choix des valeurs (Tmin, Tmax, Stolen, LowBrood, LowBat)
-Afficher les détails des curseurs (/week, /day comme sur la photo en ajoutant aussi /day au vent - Théo a oublié).
-Corriger le bug de la position des curseurs
-Marge à droite de la page
-Largeur maxi de la page (redimensionner plus petit)

**Avant que je puisse modifier de mon côté, je dois attendre que tu mettes à jour les champs des utilisateurs par contre avec les nouvelles valeurs.**

**Comment by savioarthu** [comment]
C'est configuré pour moi, j'attends que ça soit ok du côté de Mickael pour pull sur le serveur.

**Comment by savioarthu** [comment]
Point vendredi:
Bien avancé ! 

-Manque 'for' devant 4 days pour Disconnection, idem en français ('depuis')
-Manque / jour pour le vent (idem en anglais)
-Enlever la majuscule de tous les 'Jour'
-Mettre jour au singulier --> jour
-Attention en français week devient 'Month;' -> il faut écrire 'semaine'. 
-Mettre à jour dans mongo les nouvelles valeurs. 
-Corriger le bug de la position des curseurs

Ajout :
Il faudrait mettre les alertes dans l'ordre des codes que j'ai instauré (dans le fichier codeAlert.jsonà. Plus simple pour l'utilisateur de se retrouver !

**Comment by lzpons** [comment]
Je vais compléter les requêtes ci dessous avec les quelques éléments.
j'ai prévu de revoir l'aménagement de la page avec des onglets par type d'alerte. Mais on va attendre à stabiliser déjà tout ça pour le faire. De toute façon ce qu'on traite ici est un passage obligé.

voici donc mes remarques
-limiter la largeur de la page au juste nécessaire. 400/800px au pif.
-justifier les libellés des alertes à gauche, près des pictos
-rapprocher le petit (i) du libellé, les laisser néanmoins alignés à la verticale (le plus long libellé définira la positon définitive de la colonne.
-les alarmes sont par jour et non jour(s) non @savioarthu ?
-bug position curseurs, mais tu sais déjà.

![alertes](https://user-images.githubusercontent.com/41069288/69670288-e4052200-1093-11ea-8e19-33a1c7bfd9fd.png)

**Comment by savioarthu** [comment]
Alertes par jour je confirme, comme précisé plus haut.

**Comment by mickael2407** [comment]
Pour ce qui est des curseurs je sais pas trop quoi faire pour

**Comment by mickael2407** [comment]
J'ai fait les modifications, pour les curseurs j'ai modifié un détail chez moi ça à l'air de fonctionner à vous de me dire

**Comment by savioarthu** [comment]
Ok tout est bon pour moi, reste 2 détails:
1) Quel que soit la langue on a toujours 'days' pour l'alerte de déconnexion. 
<img width="839" alt="Déconnexion" src="https://user-images.githubusercontent.com/49641714/69748268-43246e80-1148-11ea-81d9-d4c4733cf67b.png">
2) Possibilité de les mettre dans l'ordre par numéro comme dans codeAlert.json ??
Ou au moins les ranger par type et non dispersé comme actuellement.

**Comment by lzpons** [comment]
Pour le rangement j’ai prévu d’organiser par onglets mais on verra ce nouveau design lorsqu’on aura levé les bugs/besoins urgents.
En attendant classe-les dans cet ordre :
ruche
méteo
capteurs

Le 27 nov. 2019 à 19:02, Arthur Savio <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ok tout est bon pour moi, reste 2 détails:

  1.  Quel que soit la langue on a toujours 'days' pour l'alerte de déconnexion.

[Déconnexion]<https://user-images.githubusercontent.com/49641714/69748268-43246e80-1148-11ea-81d9-d4c4733cf67b.png>

2) Possibilité de les mettre dans l'ordre par numéro comme dans codeAlert.json ?? Ou au moins les ranger par type et non dispersé comme actuellement.

**Comment by mickael2407** [comment]
Trié par catégories (hive, weather & sensor).

**Comment by savioarthu** [comment]
Point final, voilà ce qu'il reste :
 
1) Quel que soit la langue on a toujours 'days' pour l'alerte de déconnexion. 
<img width="839" alt="Déconnexion" src="https://user-images.githubusercontent.com/49641714/69748268-43246e80-1148-11ea-81d9-d4c4733cf67b.png">
2) Ajouter 'for', 'depuis', 'desde' en espagnol ?? (@lzpons) devant l'alerte de déconnexion. (demande de Theo).
3) @lzpons voulait un tri dans cet ordre : ruche/meteo/capteurs. C'est encore mélangé à l'heure actuelle. Voici un exemple de configuration en attendant les sous-onglets : 

Miellée (ok)
Essaimage (ok)
Couvain (ok)
risque essaimage (ok)
Perte poids (ok)
Gain poids (ok)
Faible Tint (à déplacer ici)
Forte Tint (à déplacer ici)
Faible Hint (à déplacer ici)
Forte Hint (à déplacer ici)
Batterie (à déplacer ici)
---
Pluie (à déplacer ici)
neige (à déplacer ici)
vent (à déplacer ici)
Période froide (à déplacer ici)
Station météo (à déplacer ici)
---
Ruche volée (à déplacer ici)
Déconnexion(à déplacer ici)

**Comment by lzpons** [comment]
pour moi la batterie va également dans le 3eme groupe

**Comment by lzpons** [comment]
D'autres ajustements de format sont nécessaires mais déjà rapportés dans l'issue qui touche à l'aménagement sur smartphone.
On ferme.

**Comment by savioarthu** [comment]
Pourquoi avoir fermé @lzpons  alors qu'il reste des corrections à faire ? ;)

**Comment by lzpons** [comment]
on les retrouvera dans #70
