### ISSUE TITLE
Affichage sur photo rucher

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#58]
Vérifier les onglets 'Poids', 'Couvain' et 'Sensor'. Souvent rien ne s'affiche.

<img width="817" alt="Pas de Capteur" src="https://user-images.githubusercontent.com/49641714/69446120-09bcbf00-0d54-11ea-8909-cadb5ac7e27e.png">
<img width="794" alt="Pas de poids" src="https://user-images.githubusercontent.com/49641714/69446129-0c1f1900-0d54-11ea-87cd-0b7833dbbf0d.png">

**Comment by mickael2407** [comment]
En admin cela ne fonctionne pas

**Comment by savioarthu** [comment]
Ok pour le mode admin, pour le reste cela fonctionne bien.

**Comment by lzpons** [comment]
on peut clore?
