### ISSUE TITLE
Alertes par e-mail 

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#60]
Les alertes déçoivent parvenir par email aux utilisateurs.
Il nous faut un email à double encodage? Est ce mandataire?
Dans un premier temps faire simple avec le mail de l’utilisateur

Il faudra voir ensuite pour qu’il puisse choisir plusieurs adresses et des fréquences d’envoi

**Comment by savioarthu** [comment]
Mise en place ok.
En test sur mon adresse  pendant quelques jours puis si c'est ok déploiement aux utilisateurs.

**Comment by lzpons** [comment]
Je propose de tester asap avec Rich, Theo et moi.
je voudrais voir le fond mais aussi la forme de ce qui est envoyé.

**Comment by savioarthu** [comment]
Je m'en occupe asap.

**Comment by savioarthu** [comment]
Question : tu veux recevoir les alertes de tout le monde dans un premier temps ? Ou juste les tiennes et sur quelle adresse ?

**Comment by savioarthu** [comment]
Question @lzpons  : tu veux recevoir les alertes de tout le monde dans un premier temps ? Ou juste les tiennes et sur quelle adresse ?

**Comment by lzpons** [comment]
seulement les miennes et sur mon adresse mellisphera.
tu me diras, avec le hub en rade j’en aurais pas trop.. mais je vais le remettre en service ce WE.

Lorenzo

Le 27 nov. 2019 à 19:04, Arthur Savio <notifications@github.com<mailto:notifications@github.com>> a écrit :


Question @lzpons<https://github.com/lzpons> : tu veux recevoir les alertes de tout le monde dans un premier temps ? Ou juste les tiennes et sur quelle adresse ?

**Comment by savioarthu** [comment]
Tu confirmes l'adresse: lorenzo@mellisphera.com ? 
Pas de soucis, je mettrai ça en place pour toi ce week end.

**Comment by savioarthu** [comment]
C'est maintrnant fait, en attendant d'un formattage défini et d'une méthode de choix.

**Comment by lzpons** [comment]
je ferme ce fil. On se mettra autour de la table pour définir la suite pour ce sujet.
