### ISSUE TITLE
Améliorations de format dans melliCharts

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#61]
Quelques ajustements dans melliCharts
1- espacer les deux lignes de texte qui sous les calendriers contiennent les moyennes de la période
2- mettre les libelles des champs humidité (ruche et météo) en accord
--- Humidité interne max
--- Humidité externe max
--- Humidité externe min
on ne met pas de "%" car aucun des autres champs affiche des unités, qu'on retrouve de toute façon au survol. On met pas "relative" non plus pour la même raison.
3- renomer le libelle de la serie "weathersource (broodminder)" en enlevant simplement "(broodminder)" qui n'apporte pas plus d'info
4- sur l'arbre afficher le picto des ruches SANS abeilles
5- calendrier sélecteur de dates
--- changer le fond bleu par fond gris ou gris clair ou blanc? (cohérent melliUX)
--- déplacer les périodes " 9 mois" et "1 an" (pas 1 année) dans la 3eme colonne 
--- faute de frappe sur bouton Aplliquer => Appliquer et en anglais aussi Aplly => Apply
6- mettre un titre au graphique de couvain (cohérence avec l'espace "ruches" qui a des titres sur chaque objet) : "Evolution journalière du couvain" ou "Daily brood progression" ou "evolucion diaria de la cria"
7- classer les ruches par ordre alphabétique sur l'arbre, sinon c'est trop dur!
Voila ce sont des petits détails mais ils rendent l'expérience plus fluide.

**Comment by lzpons** [comment]
j'ai ajouté le point 7 ci dessus.

**Comment by mickael2407** [comment]
Je ne sais pas si l'on a l'icone ruche sans abeilles

**Comment by savioarthu** [comment]
-Pour le picto, il est sur git à la même place que les autres dans Doc.
-Pour les champs humidités, faire attention à vérifier en anglais et espagnol si la traduction est correcte avec la nouvelle orthographe. 
-Pour WeatherSource, je vais m'en occuper quand je reviens, c'est rapide. 
-Attention le champ de sélection date n'est pas traduit en espagnol. 
-1 an ne prend pas de 's'. 
-Appliquer à la place de Aplliquer. Idem en anglais.
-En espagnol et en français (PAS en anglais), il faut espacer les ':' du texte pour les moyennes.

**Comment by mickael2407** [comment]
Finis pour moi

**Comment by lzpons** [comment]
Tout est bon a deux petits détails près

3- renomer le libelle de la serie "weathersource (broodminder)" en enlevant simplement "(broodminder)" qui n'apporte pas plus d'info => @savioarthu 

4- sur l'arbre afficher le picto des ruches SANS abeilles
il y est mais il apparait coupé sur les pieds, réduire la taille d'image.

![Capture d’écran 2019-12-04 à 23 20 02](https://user-images.githubusercontent.com/41069288/70186643-a08e6180-16ec-11ea-9838-cef28b1a8cfc.png)

**Comment by savioarthu** [comment]
Yes c'est dans ma liste de choses à faire pour WeatherSource !

Et je rajoute des détails pour compléter @lzpons : 
1) Il reste un relatif en espagnol à enlever
<img width="251" alt="Nom" src="https://user-images.githubusercontent.com/49641714/70187739-3c20d180-16ef-11ea-9e53-b45fa6545216.png">

2) Espacement ':' en espagnol et en français (pas en anglais) sur tous les textes.
<img width="210" alt="Espacement" src="https://user-images.githubusercontent.com/49641714/70187856-84d88a80-16ef-11ea-835d-01d2bb529154.png">

3) Certains textes des sommes/moyennes ne sont pas espacés comme les autres. Je n'ai vu le cas que pour les précipitations et weight_income.
<img width="265" alt="Non espacé weight" src="https://user-images.githubusercontent.com/49641714/70187924-acc7ee00-16ef-11ea-82b4-f61b995dbe95.png">
<img width="262" alt="Non espacé précipitations" src="https://user-images.githubusercontent.com/49641714/70187927-acc7ee00-16ef-11ea-8bf8-96be8d3a9714.png">

**Comment by lzpons** [comment]
Je vois toujours des pictos de ruche découpés, sans pieds.

**Comment by savioarthu** [comment]
Je fais WeatherSource demain matin !

Et il reste toujours ce que j'ai dit juste au dessus :
1) Il reste un relatif en espagnol à enlever
<img width="184" alt="Nom espagnol src="https://user-images.githubusercontent.com/49641714/70387104-1b7fa280-19a1-11ea-8d99-214ad3887ed1.png">


2) Espacement ':' en espagnol et en français (pas en anglais) sur tous les textes.
<img width="210" alt="Espacement" src="https://user-images.githubusercontent.com/49641714/70187856-84d88a80-16ef-11ea-835d-01d2bb529154.png">

**Comment by savioarthu** [comment]
Je fais WeatherSource demain matin !

Et il reste toujours ce que j'ai dit juste au dessus :
1) Il reste un relatif en espagnol à enlever
<img width="357" alt="Nom espagnol" src="https://user-images.githubusercontent.com/49641714/70387113-3fdb7f00-19a1-11ea-95af-752acd66c961.png">



2) Espacement ':' en espagnol et en français (pas en anglais) sur tous les textes.
<img width="210" alt="Espacement" src="https://user-images.githubusercontent.com/49641714/70187856-84d88a80-16ef-11ea-835d-01d2bb529154.png">

**Comment by savioarthu** [comment]
Finalement j'ai eu le temos de faire le point 3, c'est bon de mon côté !

**Comment by savioarthu** [comment]
Tu as commit ?
Tout à l'heure tu m'as dit que c'était bon mais sur mon PC je vois toujours 'relativa'.

**Comment by savioarthu** [comment]
C'ets ok.
