### ISSUE TITLE
MelliUx se souvient du dernier rucher selectionné par l'utilisateur

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#62]
Enregistrer en base de données le dernier rucher visualisé pour pouvoir le restituer à l'utilisateur lors du prochain login.
Dans mon cas j'atérris toujours sur un rucher que j'utilise pas et la première chose que je fais est le changer. Il serait plus fluide d'atterrir sur mon rucher habituel.

**Comment by savioarthu** [comment]
Entre MelliUx et Mellicharts, le choix est conservé. Mais lors d'une nouvelle connexion, on arrive toujours sur le rucher HENRY2 et non GUINDALOS.

**Comment by savioarthu** [comment]
Fonctionne
