### ISSUE TITLE
Les notes de rucher effacées apparaissent toujours sur le calendrier

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#63]
J'ai saisi une note test que j'ai ensuite effacé. Je constate qu'elle est tjrs visible sur le calendrier mais pas sur la liste. mystère?
- vérifier cohérence notes saisie/effacées vs affichage calendrier

- je profite également de ce tiket pour proposer les ajustements graphiques suivants pour plus de clarté (voir capture ci dessous)
--- aligner le drop down liste ruchers avec boutons en dessous
--- centrer pictos sur la largeur de la sidebar
--- déplacer date calendrier près de la photo

![Capture d’écran 2019-11-26 à 20 58 39](https://user-images.githubusercontent.com/41069288/69673084-d357aa80-1099-11ea-907c-01365c5433ad.png)

**Comment by mickael2407** [comment]
C'est compliqué le calendrier et le tableaux de notes ne sont pas sur la même page je n'ai  pas encore trouvé la bonne manière de faire

**Comment by lzpons** [comment]
ça marche, cool!
