### ISSUE TITLE
Premiere connexion avec repartition auto de ruches

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#67]
Je viens de me connecter sur le compte de bernat et constate que les ruches sont reparties de façon un peu aléatoire. Je ne sais pas si c'est ma première connexion sur MS ou pas. Mais normalement à l'import (le 1er) on place les ruches sur plusieurs rangées.

On peut vérifier que cela marche proprement? même avec 20 ruches?
C'est important pour le déploiement US avec ceux qui en ont déjà plusieurs.

![Capture d’écran 2019-11-30 à 20 52 44](https://user-images.githubusercontent.com/41069288/69905437-b7af1580-13b3-11ea-95b5-0e3a1ac7dd5e.png)

**Comment by mickael2407** [comment]
J'ai refait la fonction cela devrait être mieux

**Comment by savioarthu** [comment]
A tester avec un nouveau compte, tu me montres ce que ça donne ou @lzpons  ? Pour qu'on puisse fermer.

**Comment by lzpons** [comment]
Pas besoin de nouveau compte, un nouveau rucher suffit.
le test est KO pour moi
elles apparaissent tout en haut, empiétant sur le cadenas que je ne peux pas cliquer.
puis les deux rangées sont placées exactement pareil en x donc se marchent dessus.

Je propose:
- de faire la rangée 1 à -1/4 (axe y vers le bas non?) de la hauteur, la rangée 2 à -2/4 de la hauteur et la rangée 3 à -3/4
- de décaler la rangée 2 par rapport à la 1 d'un demi pas de x 
- de mettre 7 ruches par rangée seulement (s'il y en avait plus on les empile à la fin de la 3eme rangée?)

![Capture d’écran 2019-12-04 à 23 07 56](https://user-images.githubusercontent.com/41069288/70185873-f2ce8300-16ea-11ea-83b1-9dda235e730b.png)

**Comment by lzpons** [comment]
@mickael2407 tu pourras effacer le rucher test de mon compte MS et refaire la synchro avec MBM pour montrer que c'est bon (capture d'écran)?

**Comment by mickael2407** [comment]
@lzpons voici en recréant 20 ruche .
![Capture d’écran de 2019-12-06 08-42-15](https://user-images.githubusercontent.com/37872697/70305340-6a440580-1804-11ea-8a79-fbcdd296b29f.png)

**Comment by lzpons** [comment]
Les rangées ne sont pas en quinconce.
C’est normal que ça dépasse autant l’image?

**Comment by mickael2407** [comment]
La taille de l'image juste une petite de correction de css.
Est ce grave qu'elles ne soient pas en quinconce ?

**Comment by lzpons** [comment]
Le quinconce pas grave si c’est bien écarté. Par contre je vois que la première rangée  est toujours collée en haut. Tu peux la démarrer a -1/4 de la hauteur?

**Comment by mickael2407** [comment]
oui pas de souci

**Comment by savioarthu** [comment]
Voila donc le résultat quand je crée une nouvelle ruche. Ca convient à tout le monde ? 

<img width="665" alt="Capture d’écran 2019-12-09 à 20 03 52" src="https://user-images.githubusercontent.com/49641714/70464375-1153c600-1abf-11ea-9a0e-bd5d9911525a.png">

**Comment by lzpons** [comment]
Non, 
la 1ère rangée doit démarrer à -1/4 de la hauteur. à peu près en dessous du texte de la photo.
sinon trop de risque de marcher sur le picto de cadenas. et puis ce sera plus propre!

Plus ça va plus je me dis qu'au lieu de mettre une photo de ruches il faudrait un picto qui explicite le glisser/deposer... à réfléchir.

**Comment by savioarthu** [comment]
@lzpons ça a l'air d'etre corrigé maitenant, j'ai essayé avec 20 ruches ça fonctionnait, à toi de voir si ça te convient comme c'est.

**Comment by lzpons** [comment]
Je viens de créer TEST3 et le résultat est toujours identique.
première rangée de ruches collées tout en haut.


![Capture d’écran 2019-12-10 à 16 07 33](https://user-images.githubusercontent.com/41069288/70541378-31d75b00-1b67-11ea-80e5-44b4dfe32ec2.png)

**Comment by mickael2407** [comment]
Ca fonctionne pourtant bien chez nous

**Comment by lzpons** [comment]
tu peux te connecter et regarder sur ce rucher TEST3.
peut être partager la capture d'écran

**Comment by mickael2407** [comment]
Dernier test avec une petite correction 
![Capture d’écran de 2019-12-10 16-43-18](https://user-images.githubusercontent.com/37872697/70544357-3a7e6000-1b6c-11ea-924e-55468eae8c89.png)

**Comment by lzpons** [comment]
ça semble marcher maintenant.
je solde.
