### ISSUE TITLE
Afficher les événements directement sur les courbes de couvain

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#68]
C'est une idée qui traine dans les cartons depuis quelque temps et qui peut vraiment changer la façon dont on appréhende les données. Il s'agit d'afficher à côté de la courbe, le picto qui décrit l’événement qui a eu lieu. 

Ci dessous j'ai fait un petit photomontage pour illustrer
Faisons quelque test isolé pour voir et ensuite on décide.

![Capture d’écran 2019-12-01 à 21 26 39](https://user-images.githubusercontent.com/41069288/69919823-46d62f00-1481-11ea-8bb7-cd2dac98c54d.png)

**Comment by savioarthu** [comment]
Icone à insérer dans le graphe dans un premier temps :
_ Inspections
_ Essaimage
_ Miellée

**Comment by lzpons** [comment]
je te k'attribue @InakiUrrutia pour que tu puisses avoir le plaisir de la solder :)
