### ISSUE TITLE
Etat des devices en contexte

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#69]
Deux améliorations pour détecter d'un coup d’œil sur MelliUx les capteurs qui sont limite.

1 - Colorier en rouge le background des capteurs qui ont un niveau de batterie faible ou qui ne transmettent plus

2 - Ajouter une pastille de device pour le Hub/ws et le traiter comme un device à part entière.

**Comment by savioarthu** [comment]
En cours, lié à l'issue #69 et 12 du stack

**Comment by savioarthu** [comment]
En cours, lié à l'issue #48 et 12 du stack

**Comment by savioarthu** [comment]
Du coup, c'est ok pour le pt1 parfait, j'ai remarqué un bug de mon côté quand il y a plusieurs capteurs sur une même ruche.

Pour le pt2 le hub n'est pas encore affiché avec sa pastille.

**Comment by savioarthu** [comment]
Pt1 ok pour moi c'est bon.
@mickael2407 pour le pt1 en fait petit soucis. Il faudrait que ta requête marche comme les autres c'est-à-dire pour chaque jour une valeur différente. Actuellement ça prend les dernières valeurs par défaut uniquement et ça ne dépend pas du jour sélectionné.

Ca sera la même chose pour le Hub et sa pastille.

**Comment by mickael2407** [comment]
C'est fait

**Comment by savioarthu** [comment]
Vu, ça fonctionne impec pour les capteurs.

**Comment by savioarthu** [comment]
Je vois que les Hub apparaissent maintenant ! Du coup tu as fini ici ?

**Comment by lzpons** [comment]
ajouter couleur rouge / verte du hub selon connectivité

**Comment by savioarthu** [comment]
Vu, ok
