### ISSUE TITLE
Améliorations sur mobile

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#70]
Ecran Général
1/ placer la sidebar à gauche, comme sur desktop
2/ enlever l'icône logout de la sidebar (on s'en sert jamais et porte à confusion avec masquer sidebar)
3/ mettre la liste déroulante des ruches au centre de la barre supérieure
4/ replacer dans la sidebar le picto « ecrivez-nous » (il est en fuite ??) => au passage le mettre avec les autres tout device confondu

Ecran MelliUx
5/ Afficher au centre les boutons rucher, couvain, etc. 
5.1/ comme sur charts les formater avec fond gris et contour turquoise
6/ afficher la date au centre sur une barre en dessous (comme sur charts)
7/ Afficher la photo sur toute la largeur de l’écran

  
![image](https://user-images.githubusercontent.com/41069288/70179145-d24bfc00-16dd-11ea-9052-9145d3afb5fe.png)

Ecran MelliCharts
Ça va presque, 
8/ un peu plus d’air entre les boutons (valable pour tout device confondu)
9/ date avec un peu plus de hauteur sur le bas pour laisser rentrer les boutons
9a/ j’ajoute ce point : les plages de date prédéfinies ne marchent pas. Clic sur 1 mois et je vous toujours 2mois, etc

![image](https://user-images.githubusercontent.com/41069288/70179168-ded05480-16dd-11ea-86ef-16c7edd35f01.png)

Ecran Notifications
10/ enlever les entêtes du tableau, ils servent a peu et 
11/ resserrer la colonne « description » au maximum pour laisser un peu plus d’air à « valeur »
12/ taille de police « valeur » doit être identique à « nom ». idem pour la police des boutons ON/OFF

![image](https://user-images.githubusercontent.com/41069288/70179214-edb70700-16dd-11ea-9144-af55833150c4.png)

**Comment by mickael2407** [comment]
Mettre le menu à gauche me parais compliqué c'est intégrer dans le template de base est liée à beaucoup de css

**Comment by lzpons** [comment]
vu hier avec @mickael2407 on laisse la sidebar à droite, en supprimant le logout.
merci de passer en revue tous les points identifiés dans la liste.

**Comment by savioarthu** [comment]
Le rendu final est super !
J'ai juste un soucis sur mon iphone XS, impossible de modifier les valeurs des alertes, la barre n'est pas présente.

![79741305_537030063809378_3269536316412395520_n](https://user-images.githubusercontent.com/49641714/70387156-c85a1f80-19a1-11ea-8617-7de917a5e679.jpg)

**Comment by savioarthu** [comment]
Et ensuite, les descriptions sont coupées à gauche.
![78661803_568976913881318_5996352507943583744_n](https://user-images.githubusercontent.com/49641714/70387179-13743280-19a2-11ea-9420-5252f95c4780.jpg)

**Comment by mickael2407** [comment]
J'ai enlevé la colonne des noms en version mobile il y a toujours l'info bulle qui donne l'info 
![Capture d’écran de 2019-12-10 15-36-07](https://user-images.githubusercontent.com/37872697/70538806-fcc90980-1b62-11ea-98f9-7cbe746622bf.png)

**Comment by savioarthu** [comment]
C'est ok pour moi, c'est vérifier, ça fonctionne.
@lzpons  je te laisse vérfier de ton côté et fermer.

**Comment by lzpons** [comment]
ça marche c'est bon et fluide
@mickael je peux ajouter dans la liste deux demandes s'il vous plait?

8/ enlever l'encadré autour du menu sandwich
9/ replier automatiquement la sidebar une fois choisi le picto

**Comment by mickael2407** [comment]
C'est fait

**Comment by savioarthu** [comment]
Vérifié pour moi ça fonctionne

**Comment by lzpons** [comment]
tout me semble ok sauf que sur mon téléphone dans Analyse le sélecteur de date n'est pas centré et le menu qu'il déplie est coupé.
L'autre petit détail la barre horizontale de zoom sous le graphe de couvain qui se superpose à l'axe x. la descendre un peu plus?

**Comment by lzpons** [comment]
tout semble ok.
on solde.
