### ISSUE TITLE
Impossibile de modifier une note

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#71]
Ayant vu des caractères spéciaux bizarres sur la ruche R6 de @lzpons (sais-tu pourquoi d'ailleurs ? problème d'accent ?) , j'ai voulu modifier et impossible d'enregistrer le message modifié, je ne peux pas cliquer sur le bouton 'Enregistrer'. 

<img width="605" alt="Capture d’écran 2019-12-04 à 23 22 03" src="https://user-images.githubusercontent.com/49641714/70186840-1266ab00-16ed-11ea-8c74-4b647320a70d.png">

**Comment by mickael2407** [comment]
Ca fonctionne chez moi !

**Comment by savioarthu** [comment]
Marche sur Chrome, ne fonctionne pas sur Safari !

**Comment by mickael2407** [comment]
Il faut préciser une date sinon tu ne peut pas valider

**Comment by savioarthu** [comment]
Nop, ça ne marche toujours pas ! 
Par ailleurs, l'heure est déjà saisi sur chrome (ce qui est logique) alors qu'elle ne l'est pas sur safari. 
Ce module de date ne doit pas être sur safari et doit faire planter l'enregistrement.
