### ISSUE TITLE
Améliorarions MelliUX avec Theo

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#72]
Suite au call avec Theo d'hier, voici les points a résoudre sur MelliUx

1/ il nous a montré que les valeurs de couvain et de poids ne s'affichent pas toujours sur les pastilles (malgré que la donnée existe).

2/ la ruche L10 de Dandelion affiche 5 devices sur MS alors qu'elle n'en a que 3 d'affectés sur MBM. On affiche tout l'historique des capteurs au lieu de la configuration à l'instant t.

3/ afficher les labels des capteurs par rapport à leur position relative dans la ruche : upper, lower, under : les balances toujours en bas

4/ lorsqu'on clique la première fois sur une ruche, le calendrier de couvain apparait avec le colormap vertical pendant 1 sec et après il se remet à l'horizontal.

5/ le rucher qui se charge par défaut doit être celui sur lequel on a travaillé en dernier. stocker dans la base le dernier rucher travaillé pour le rouvrir à la nouvelle session

Pour  @savioarthu :
6/ la ruche L04 a été ajoutée le 27 aout (division) mais elle affiche des données bien avant cette date. qui viennent d'une autre ruche. Bien gérer les localisations et le t0 avec

**Comment by savioarthu** [comment]
Vu pour moi
6) je pense qu'il faut juste lancer la moulinette en mode admin, je m'en charger lundi et je vérifierais que ça fonctionne bien en prenant cette ruche pour exemple

**Comment by mickael2407** [comment]
Pour le point 5 je stocke dans de la même manière que le token de cette façon la ruche & rucher sera sauvegardé cela reviens au même que le sauvegarder dans la base mais beaucoup plus simple.

**Comment by savioarthu** [comment]
6. Ca fonctionnait déjà bien en fait mais il y a des limitations à ma fonction. En effet, quand il y a une période qui n'est affectée à aucune ruche, on laisse l'affectation par défaut à la dernière ruche en cours, ce qui est le cas pour Théo (à certaines dates, ces capteurs ne sont affectés à aucune ruche). La possibilité serait de modifier la fonction pour supprimer les données en dehors des périodes d'affectation, ce qui est un peu plus complexe à faire mais c'est possible à mon avis. Qu'en penses-tu @lzpons ?

**Comment by lzpons** [comment]
ce serait le plus propre non?
ça demande une certaine rigueur de gestion de configuration mais c’est nécessaire pour avoir les bonnes données.

On va le faire, mais pas prio de suite : On peut re-flecher dans une issue spécifique qu’on traitera le moment venu.

**Comment by savioarthu** [comment]
Je le mets dans ma liste prio 2 si j’ai le temps cette semaine je le ferais !

**Comment by mickael2407** [comment]
4, 5 fait, pour le 1 je pense avoir corrigé mais si vous pouvez tester pour vérifier

**Comment by mickael2407** [comment]
Pour le 2 j'ai essayé en affectant un capteur à une autre ruche ça bien suivit et j'ai biens toujours un capteur sur la bonne ruche

**Comment by savioarthu** [comment]
Le point 6 est bon pour moi, j'ai vérifié sur une ruche de théo c'est ok.

**Comment by mickael2407** [comment]
Pour ce qui es du 3 pour l'instant je sais pas trop quoi en faire çà demanderais du travail pour avoir ses informations

**Comment by lzpons** [comment]
1/ ça peut encore arriver mais difficile de déverminer. Si au-moins on savait où aller voir pour vérifier..
2/ on a vu qu'il s'agissait d'un cas hérité de l'historique. Administration manuelle. J'ai demandé à Theo du feedback
3/ on le laisse en stand by, pas prio.
4/ ok
5/ ok
6/ ok

On solde.
