### ISSUE TITLE
Améliorations MelliCharts avec Theo

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#73]
Suite au call avec Theo d'hier, voici les points a résoudre sur MelliCharts

1/ maintenir la ruche sélectionnée sur l'arbre lorsqu'on pase de hives => brood

2/ en revenant de brood => hive conserver la sélection de la première ruche du tableau de sélection

3/ preserver la function actuelle qui garde la sélection multiple entre brood <=> hourly

4/ sur Safari le sélecteur de date ne s'ouvre pas et on a du passer sur Firefox (pas réussi à le réproduire sur mon mac)

**Comment by mickael2407** [comment]
1, 2, 3 corrigé, je cherche plus d'info pour le 4

**Comment by lzpons** [comment]
le point 4/ n'est pas soldé à 100% il peut encore y avoir des cas où la fenêtre ne s'ouvre pas..
mais il n'y a pas d'erreur sur la console. On ferme et on verra si le bug revient souvent.
