### ISSUE TITLE
Améliorations alertes avec Theo

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#74]
voici pour les alertes

1/ renommer l'alerte par "Device disconnect or poor signal"

2/ sur l'augmentation/diminutions soudaine de poids il est plutôt centré sur du pillage et pas sur de la production à cause d'une miellée. Propose de changer les pictos par une abeille voleuse/volée comme à la banque

3/ alarme "high wind" : enlever le "/day" des unités

4/ weatherstation : s'il n'y a pas de station météo, cette alarme devrait pas être affichée

Ce" qui suit est pour @savioarthu 
5/ pourquoi il n'y a pas de réglage possible sur "cold period" et que veut dire "normal" dans la définition?

6/ Ajouter un lien vers MS et MBM en pied de page de l'email d'alerte

**Comment by savioarthu** [comment]
Vu pour moi

5) Cold Period est très difficile à paramétrer. Cette alerte dépend de plusieurs paramètres dont notamment l'hémisphère, la saison ou le mois de l'années et des valeurs fixées. Ainsi en fonction de la saison, de l'hémisphère ou du mois de l'année, ces valeurs changent. A l'heure actuelle, cela voudrait dire que l'utilisateur doit choisir ses valeurs pour chaque saison. Ainsi, si l'on veut mettre en place une configuration pour l'utilisateur il faut changer la façon dont je traite l'alerte. Par exemple en utilisant une moyenne des valeurs (mais il faut voir quelle période on prend pour se fixer cette période) etc etc. 
Cependant, je précise que le but de cette alerte est qu'elle soit déclenchée lorsqu'il y a une période de froid anormale (uniquement fin printemps/été/début automne), i.e des températures bien inférieures aux moyennes de la saison ou des nuits très froides. Il faut que je réfléchisse à comment faire plus simple et la rendre potentiellement configurable par l'utilisateur. 
Je ne suis pas sur que Théo avait compris l'alerte comme ça. Il pensait plutôt à une période très froide je crois. 
6) je m'en occupe lundi

**Comment by lzpons** [comment]
5. Si l’alerte est complexe, pas besoin de la laisser en paramétrage. Par contre il faudra toujours rendre explicite la fonction et les critères. Par exemple dire que froid = -10°C en dessous des normales de saison.??
Pour que chacun puisse comprendre à peu près de quoi il en retourne.

**Comment by savioarthu** [comment]
5. Il faut que je regarde plus en détails de toute façon mais en gros oui on pourrait dire que ce sont des faibles températures externes (approximativement -10°C en dessous on va dire) vis à vis des normales de la saison en cours (printemps, été, automne).

**Comment by mickael2407** [comment]
1,3 fait
Pour le 4 la station météo j'ai ajouté un paramètre dans les userPref mais je n'ai pas encore mis dans la page userPref pour que l'utilisateur le modifie

**Comment by savioarthu** [comment]
6. Lien vers MS/BM ok, c'est bon pour moi.

Pour le 2. en te relisant je me suis dis que je pouvais aussi faire l'icone en svg mais nous n'avons aucune alerte qui dit s'il y a une augmentation ou diminution soudaine de couvain. Juste une alerte signalant un faible couvain (en dessous de 30% par exemple). De quelle alerte parlais-tu ?

**Comment by lzpons** [comment]
de l’alerte de période froide.

**Comment by savioarthu** [comment]
Je ne comprends pas ton message alors :
« 2/ sur l'augmentation/diminutions soudaine de couvain il est plutôt centré sur du pillage et pas sur de la production à cause d'une miellée. Propose de changer les pictos par une abeille voleuse/volée comme à la banque »

**Comment by lzpons** [comment]
C'était une coquille, c'est augmentation/diminution soudaine de **poids**.

**Comment by savioarthu** [comment]
Point 1, 3, 4, 5, 6 sont ok !

**Comment by mickael2407** [comment]
@lzpons Tu pourra me fournir l'icon pour fermer cette issue

**Comment by lzpons** [comment]
je ferme cette issue et en crée une novelle dédiée aux pictos manquants
