### ISSUE TITLE
Suppression rucher BM/MS

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#75]
J'ai supprimé un rucher entier à partir de BroodMinder (j'ai supprimé le rucher directement ce qui a supprimé ruches et capteurs en même temps) -> le rucher TEST de Lorenzo composé des ruches 1 à 20. 
Cependant, il est encore présent sur Mellisphera. Entre temps, j'ai crée un nouveau rucher TEST, @lzpons  a donc deux ruchers tests :p 

<img width="110" alt="Capture d’écran 2019-12-09 à 20 07 25" src="https://user-images.githubusercontent.com/49641714/70464628-8d4e0e00-1abf-11ea-9641-93c71b9d01d3.png">
<img width="250" alt="Capture d’écran 2019-12-09 à 20 07 30" src="https://user-images.githubusercontent.com/49641714/70464630-8de6a480-1abf-11ea-8eee-9283cd83d365.png">

**Comment by mickael2407** [comment]
Je pense à un problème dans les changelog qui à empêché la suppression j'ai déjà fait cette action avant et çà avais très bien fonctionné, j'ai vue que le compte à lorenzo avais des changeLogs non appliqué chez nous j'ai fais quelque correction c'est peut être la cause du problèmes à voir

**Comment by savioarthu** [comment]
Fonctionne de nouveau !
