### ISSUE TITLE
Responsive sur écran avec basse résolution

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#76]
En discutant avec Bernat au teléphone, il me disait ne pas voir les calendriers sur son ordi de bureau. A la fin j'ai compris qu'ils étaient empilés comme sur un smartphone. Pourtant il a un écran suffisamment gros (voir photos).

C'est certainement une histoire de media query, une idée pour pallier à ça?
Sur les photos on voit bien qu'il y aurait de la place pour les ruches à gauche et un calendrier à droite. 

Peut être empiler les calendriers à droite de l'arbre des ruches? et si c'est encore trop petit les mettre dessous?

![3ee2d31d-ba5e-4c1a-bba9-e831e66ed5f8](https://user-images.githubusercontent.com/41069288/70473913-0e160580-1ad2-11ea-953c-e5c93630b9e4.JPG)
![ac2e61f5-884b-458f-b931-29cfdba2e2c7](https://user-images.githubusercontent.com/41069288/70473918-0e160580-1ad2-11ea-939a-69dad122156d.JPG)

**Comment by mickael2407** [comment]
J'ai fait des ajustement, Bernat pourrais nous dire si il y'a du mieux

**Comment by lzpons** [comment]
sur ma machine la div avec les ruches est plus rétrécie qu'avant du coup bcp de retours à la ligne.  surtout qu'elle se rétrécit encore plus au fur et à mesure qu'on réduite la fenêtre.
Je propose de l'élargir un peu et de garder la largeur presque constante.

Ensuite les calendriers se mettent bien l'un sur l'autre à côté de l'arbre des ruches. c'est bien la cible comme ça. Seulement il me semble qu'on peut allonger le moment de la transition entre ce stade et le stade complètement empilé (ruches puis calendriers en dessous).


![Capture d’écran 2019-12-10 à 17 13 12](https://user-images.githubusercontent.com/41069288/70547078-977c1500-1b70-11ea-8593-e971761a3c3e.png)

**Comment by mickael2407** [comment]
J'ai ajuster à voir

**Comment by lzpons** [comment]
On pourrait encore peaufiner pour certaines tailles d'écran iPad par exemple. Sauf qu'il faut revoir la division qui contient le calendrier qui est superposée à l'arbre des ruchers. On en reste là pour l'instant.
