### ISSUE TITLE
Le rucher demo n'affiche pas les capteurs

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#78]
En regardant de plus près, le rucher demo n'affichait ni couvain, ni poids ni capteurs.
Après plusieurs clics j'ai vu apparaitre couvain et poids mais jamais les capteurs.

Je soupçonne qu'il y ait un pb avec les droits en plus du bug d'affichage déjà remonté par Theo.

Quant aux notes, est-il possible de les faire apparaitre, en lecture seule?

![Capture d’écran 2019-12-09 à 23 55 55](https://user-images.githubusercontent.com/41069288/70480311-ae265b80-1adf-11ea-90ff-31880b611cfb.png)

**Comment by mickael2407** [comment]
Les capteurs sont récupéré avec le userId doc c'est normal

**Comment by lzpons** [comment]
on peut pas désactiver des choses alors que le but du rucher demo est de les montrer.
nécessite qu'on y réfléchisse un peu plus...

**Comment by savioarthu** [comment]
On en fait quoi de cette issue ? @lzpons 
Actuellement, on a pas l'affichage des capteurs ni du Fitness sur le rucher demo dans Apiary. 
Je ne sais pas la difficulté technique de cela pour @mickael2407.

**Comment by lzpons** [comment]
je ne sais répondre sur la faisabilité/difficulté technique. Mickael dit qu'il requete par userid donc en ce sens ça parait contraint. Soit vous trouvez une autre solution...

Ah, je pense qu'une possibilité est de vraiment faire une copie de ce rucher demo dans chaque compte. C'est à dire ne pas pointer vers un seul rucher mais copier ses données dans le compte de l'utilisateur. On a déjà évoqué qu'au lieu de connecter mes ruches à ce rucher il faudrait avor un rucher rempli sur 12 mois avec des evenements type et des notes type. Un vrai appartement témoin qui montre toutes les fonctions. Lorsqu'un user se connecte on lui copie tout ça dans son tout premier rucher. A vous de voir si les capteurs ne mettent pas le bazar et si la passerelle avec mbm est épargnée.

**Comment by savioarthu** [comment]
Fitness et Sensor ok
