### ISSUE TITLE
Quelques améliorations après la revue avec Rich

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#79]
1a/ dans les préférences de langue, mettre un drapeau US au lieu de GB. AU passage prendre des icônes carrés comme ici https://www.flaticon.com/authors/flags/rectangular c'est plus facile a trouver. Les organiser ainsi EN / FR / ES et les placer à la verticale comme les autres paramètres, avec un bouton radio pour les choisir. Actuellement on voit mal lequel est sélectionné.

1b/ dans les préférences ajouter le format de date MM/DD/YYYY

2/ quant on déplie les ruchers la flèche doit aller vers le bas, repliés vers la gauche.

3/ en arrivant dans melicharts le calendrier central était plus gros que les autres avec 2 semaines de plus

4/ les pastilles rondes d'alerte qui s'affichent sur les pastilles sont a déconnecter. Elles ne sont pas utilisées. => commenter le code.

Des comportements un peu étranges
A/ à la connexion avec le compte juice il est atérri sur un interface en français !? une idée?

B/ on a eu le demo apiary avec les ruches en double sur firefox. Pour moi et pour lui ensuite sur chrome le problème n'y était pas, donc une question de session.

![Capture d’écran 2019-12-13 à 22 40 06](https://user-images.githubusercontent.com/41069288/70836129-885ec680-1dff-11ea-8b3f-d14d867b7781.png)

**Comment by mickael2407** [comment]
4.a surement une erreur de ma part 
4.b jamais eu ce cas

**Comment by savioarthu** [comment]
1b, 3, 4 ok
Pour 1a ce n'est pas exactement ce que @lzpons voulait mais moi ça me convient comme ça je trouve ça clair mais à valider quand même. 
Pour 2, idem, ça replie vers le haut et non la gauche, mais je pense que c'est clair aussi.

**Comment by lzpons** [comment]
ça me semble ok en l'état.
