### ISSUE TITLE
Pictos manquants

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#80]
Produire et mettre à jour pictos sur le site
- abeille volée
- abeille voleuse
- ruche volée (masque)
- ruche morte (RIP ou tête de mort/abeille)
- picto capteurs : W, T, Hub, Station météo pour y faire référence
- picto varroa / oxalique
- picto sun/moon
- abeille fitness

**Comment by mickael2407** [comment]
Ajouter les pictos fournis sur slack

**Comment by lzpons** [comment]
livrés
    ruche volée (masque)
    picto capteurs : W, T, Hub, Station météo
    picto sun/moon
    abeille fitness

manquants
    ruche morte (RIP ou tête de mort/abeille)
    picto varroa / oxalique

abandonnés
   abeille volée
   abeille voleuse

**Comment by savioarthu** [comment]
Du coup, y'a-t'il un intérêt à un icône ruche morte puisqu'on a intégré le processus dans Fitness (couleur noire à l'affichage) ? 
Quand on aura le calendrier Fitness, on pourra même retracé le cheminement menant à la mort. Donc on est alerté par ce fait. Surtout qu'être alerté une fois que la ruche est morte n'a pas grand intérêt au final, ce qu'on veut c'est pouvoir agir et non subir à retardement.

**Comment by lzpons** [comment]
j'ai mis le picto ruche morte à jour et j'en suis a peu près satisfait. On peut l'intégrer pour qu'il apparaisse dans le calendrier.

**Comment by lzpons** [comment]
OK, il faut que je vois pour faire le picto varroa. je n'ai pas pu sortir qqch de potable avec les svg que j'ai récupéré. donc faut trouver une autre alternative

**Comment by savioarthu** [comment]
Update :
-Picto varroa / traitement acide oxalique
-Picto Ajout de Hausse
-Picto Retrait de Hausse

**Comment by lzpons** [comment]
c'est solde !
