### ISSUE TITLE
Configuration du rucher pour Theo avec capteurs déplacés

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#81]
Certains capteurs de Theo continuent à apparaitre alors qu'ils sont partis ailleurs  (les trois derniers du listing ci dessus).
 
Vérifier si ça se résorbe avec nouvelle réimportation du rucher?

<img width="1472" alt="Screen Shot 2019-12-13 at 17 38 46" src="https://user-images.githubusercontent.com/41069288/70837434-f73e1e80-1e03-11ea-92a3-5891ab44d592.png">

**Comment by mickael2407** [comment]
Probléme résolue j'ai mis à jours tous les deviceLocation de mongo et filtrer pour afficher seulement les capteurs qui sont actuellement affectés

**Comment by savioarthu** [comment]
A confirmer par theo dans les prochains jours.

**Comment by savioarthu** [comment]
Confirmé par Théo.
