### ISSUE TITLE
Regler le pb de page blanche à l'ouverture

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#82]
Pb avec le token qui reste actif?

**Comment by savioarthu** [comment]
Ca à l'air de fonctionner pour moi, à voir dans les prochains jours si c'est toujours le cas ;)

**Comment by savioarthu** [comment]
J’ai remarqué qu’à la première connexion après expiration du token, la page Alerte reste blanche, je dois rafraîchir pour qu’elle s’affiche. À confirmer mais j’ai eu le soucis 2 fois (sur safari téléphone et sur safari Mac)

**Comment by mickael2407** [comment]
C'est réglé si voulez vérifié que cela fonctionne sur chrome ouvrez l'inspecteur:
![Capture d’écran de 2019-12-18 11-43-16](https://user-images.githubusercontent.com/37872697/71079480-9e67e080-218b-11ea-8f12-b6197317c431.png)
il suffit de modifier "TOKEN_KEY" soit en la modifiants ou le supprimant tous simplement plus qu'a rafraîchir la page

**Comment by savioarthu** [comment]
Tout fonctionne.
