### ISSUE TITLE
Ajustements sur mobile +

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#83]
Voici quelques petits dysfonctionnements constatés sur mobile

1/ Il y a une div blanche entre le menu de la sidebar et la page principale.
Lorsqu'on replie le menu, elle reste visible et rogne la partie gauche de l'affichage.
Il faudrait carrément supprimer cette division si c'est possible.
![Capture d’écran 2019-12-14 à 00 10 27](https://user-images.githubusercontent.com/41069288/70837924-25bcf900-1e06-11ea-8ab9-861a301148f1.png)

2/ le contenu apparait beaucoup trop bas maintenant. réduire le gap énorme entre les ruches et les calendriers.
![IMG_4292](https://user-images.githubusercontent.com/41069288/70837973-5dc43c00-1e06-11ea-9d13-4d968d0dd8bb.PNG)

3/ incohérence de format de dates, une en EU l'autre en US. Pas sur qu'on ait la main pour le faire, mais il faudrait, sinon c'est troublant. comme ici 14/11 et 11/14 
![IMG_4293](https://user-images.githubusercontent.com/41069288/70837971-5ac94b80-1e06-11ea-9e8a-04a841591bc6.PNG)

**Comment by mickael2407** [comment]
2 réglé, 1 je n'ai pas ce cas la ni sur chrome en vue mobile ou sur mon téléphone

**Comment by lzpons** [comment]
on va regarder ensemble en fin de semaine.

**Comment by lzpons** [comment]
1/ et 2/ ok c'est parfait.
3 / on vit avec?
4/ @mickael2407 je remarque un autre souci qui est que les périodes prédéfinies 51 mois, 2 mois) ne marchent pas sur mobile. le calendrier fait tjrs 2 mois.

**Comment by mickael2407** [comment]
Je pense que ce problèmes était liée au l'ancienne méthode permettant de faire commencer les calendrier  un lundi à vérifié ...

**Comment by savioarthu** [comment]
C'est bon pour le pt 4.
Pour le pt3 au final c'est pas dérangeant pour l'instant, on ouvrira une autre issue s'il le faut. Je ferme.
