### ISSUE TITLE
Pictos sur la photo du rucher

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#84]
Pour pouvoir insérer une foto du rucher avec une tablette il faut un bouton/menu contextuel.
Mettre cote à cote trois pictos en haut à droite de la photo du rucher 
- [cadenas] pour déplacer les ruches

- [image] pour insérer une photo via un menu de sélection qui s'ouvre lorsqu'on clique dessus (sur desktop et surtout sur tablette, smartphone)
![Capture d’écran 2019-12-14 à 00 42 06](https://user-images.githubusercontent.com/41069288/70838883-8f3f0680-1e0a-11ea-95d4-b0c0e3f82cb5.png)

- [pdf] ou [tableau] pour sortir un listing pdf des ruches en mode tableau (pop up > puis print? ou direct pdf?
![Capture d’écran 2019-12-14 à 00 41 18](https://user-images.githubusercontent.com/41069288/70838864-85b59e80-1e0a-11ea-85c4-f6a8ed82b929.png)

prends-les ici
[908.eps.zip](https://github.com/mellisphera/mellisphera-web/files/3963112/908.eps.zip)

**Comment by savioarthu** [comment]
Cadenas / Images --> Ok !

Manque PDF

**Comment by savioarthu** [comment]
issue #123 évoque le listing pdf, je ferme ici.
