### ISSUE TITLE
Organiser les json pour la traduction

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#85]
Structurer jsons pour faciliter la traduction.
Pas besoin d'un json monolitique, il peut en y avoir deux ou trois, bien identifiés.
objectif : contenir 100% des éléments nécessitant traduction.

Quand c'est prêt notifier Marcel qu'il peut se lancer en NL

**Comment by savioarthu** [comment]
Il faudra ici rajouter codeFitness / codeAlert et codeStatus lié avec le stack si ça n'a pas été fait. 
[Archive.zip](https://github.com/mellisphera/mellisphera-web/files/4005595/Archive.zip)

**Comment by lzpons** [comment]
fait
