### ISSUE TITLE
Ruches manquantes sur l'affichage

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#87]
Alors que sur melliCharts on voit les 20 ruches de Rafal Vell (Bernat) sur melliUx il manque la RV5, RV10 et RV13*

Sur la console on voit bien passer ces ruches dans les print avec les capteurs. Mais plus loin il y a des erreurs, je ne sais pas s'ils sont liés.

![Capture d’écran 2019-12-16 à 22 33 30](https://user-images.githubusercontent.com/41069288/70944793-17fcb300-2054-11ea-9102-3e0a08d06a64.png)

**Comment by mickael2407** [comment]
Ok je viens de regarder en faite les ruche manquante était juste superposée dans melliUx
![Capture d’écran de 2019-12-17 09-19-11](https://user-images.githubusercontent.com/37872697/70977510-62ab1900-20ae-11ea-990b-71a8d7f2a37c.png)

**Comment by lzpons** [comment]
Dis donc la superposition devait être parfaite !
J’en avais déplacé quelques unes pour voir mais sans les trouver ni y croire non plus.

C’est moi qui les avait mises en rangée il y a quelque jour. À mon avis il doit y avoir un petit bug sur le positionnement. On y fera attention par la suite.

**Comment by savioarthu** [comment]
C'est donc réglé ?

**Comment by lzpons** [comment]
Pas sûr, je viens de créer le rucher TEST4 et lors de la connexion à MS j'ai la montre qui tourne et des erreurs. J'ai déjà vu ça avant. Lorsqu'on se reconnecte à nouveau ça marche. mais pas la première fois. c'est un bug

![Capture d’écran 2019-12-27 à 12 20 11](https://user-images.githubusercontent.com/41069288/71515445-8129c500-28a3-11ea-8e47-52249dadaf5a.png)

Ensuite pour ce qui est de la superposition des ruches, non elles ne se superposent pas mais elles ne sont pas classées dans l'ordre non plus. J'ai crée A,B,C....J,K,L,M. Alros qu'on affiche BLACDG...On peut les ordonner?


![Capture d’écran 2019-12-27 à 12 21 33](https://user-images.githubusercontent.com/41069288/71515460-9a327600-28a3-11ea-99af-08b8ad6df90a.png)

**Comment by mickael2407** [comment]
L'ors de la récupération dans les change logs les ruches sont récupéré par ordre de création de la plus récente à la plus anciennes 
ex:
```        "hiveCreate": [
            {
                "hiveId": "vcwcFHYFnPKrW7Pl6vE3",
                "apiaryId": "jP9eGlxCfyc3Ek99mcmx",
                "description": "",
                "name": "j",
                "createDate": 1578320451,
                "hidden": false
            },
            {
                "hiveId": "vX6qskwym8Dl1bnfEWps",
                "apiaryId": "jP9eGlxCfyc3Ek99mcmx",
                "description": "",
                "name": "k",
                "createDate": 1578320455,
                "hidden": false
            },
            {
                "hiveId": "6esQMQgtWUGNgrji7VSU",
                "apiaryId": "jP9eGlxCfyc3Ek99mcmx",
                "description": "",
                "name": "i",
                "createDate": 1578320444,
                "hidden": false
            }
        ]
```
cela concerne juste melliUx car les ruches sont triée par ordre alphabétique

**Comment by lzpons** [comment]
dans l'exemple ci dessous le classement n'est pas par date de création
on a 157xxx451 puis xxx455 puis xxxx444 par contre in voit bien que cela correspond à i,j,k docn l'ordre de création.
Je les ai crées aussi dans l'ordre donc elles devraient y apparaitre si c'était pas date. A mon avis tu es bon pour les trier par ordre alphabétique "name" ou peut être par createDate comme tu proposes. :) les deux doivent marcher

**Comment by mickael2407** [comment]
Mais et-ce vraiment important de les trié ce n'est pas un listing

**Comment by lzpons** [comment]
oui il le faut !

**Comment by mickael2407** [comment]
A voir si ça fonctionne

**Comment by savioarthu** [comment]
<img width="778" alt="Capture d’écran 2020-01-23 à 21 53 00" src="https://user-images.githubusercontent.com/49641714/73022926-c43b7180-3e2a-11ea-8890-31d288f1b8bb.png">

Rien de mieux q'un test pour vérifier ! Bien classé, je ferme !
