### ISSUE TITLE
Les notes ne prennent pas en compte les caractères accentués

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#88]
Rucher Rafal Vell (Bernat)
Les notes sur RV06, 08, 09 présentes des défauts toujours avec les accents.
je ne sais pas si elles ont été produites sur mbm ou sur ms, mais je parie mbm car deux d'entre elles ont des balises de format que seul l'interface de mbm sait appliquer.

A noter que le clavier est un qwerty avec composition du char accentué avec la lettre + la touche d'accent.

![Capture d’écran 2019-12-16 à 22 38 32](https://user-images.githubusercontent.com/41069288/70945160-dfa9a480-2054-11ea-9b27-d5973a48bec2.png)

**Comment by savioarthu** [comment]
Je rajoute dans cette note qu'il faut voir (ou prévenir) avec Amanda. Il y a un soucis de transfert de notes (apiculteur13 par exemple) de MBM vers MS. Et donc en attente d'une réponse d'Amanda concernant l'écriture d'une note de MS vers MBM pour les accents.

**Comment by lzpons** [comment]
voici un retour de Dimae10 qui a fait quelques tests de son côté:
c'est lorsqu'on fait un nouveau login à MS que le souci apparait et pas lors du transfert MS=>MBM
Sachant que les notes accentuées crées dans MBM passent sans souci..
A creuser.


> En effectuant quelques tests, je suis tombé sur le problème d’accent de votre github
> Mes tests ont été effectués par Dimae10 sur le rucher Montherod et ruche Rouge
> Bug 88 Les notes ne prennent pas en compte les caractères accentués
> En complément de la note de savioarthu du 24 Mar
> Voici ce que j’ai constaté
> 1 - Dans MS ajouter le texte « Créé note dans MS coupé les cadres à mâles » à 23h21 6.05.2020, sauvegardé pas de problème d’accent.
> 2 – Dans MBM le texte de 23h21 du 06.05.2020 à le problème d’accent
> 3 – Dans MS je rafraîchis la page pas de problème d’accent avec mon texte de 23h21
> 4 – Je me déconnecte de MS et je me reconnecte dans MS le problème d’accent apparaît 06/05/2020 23:21       Cr�� note dans MS coup� les cadres � m�les
> 5 – Sur MBM après un rafraîchissement de la page le problème d’accent est également présent
> Mais les textes avec accents créés dans MBM gardent les accents après le transfert dans MS
> Si ces quelques lignes peuvent vous servir.

**Comment by lzpons** [comment]
Quelques compléments par rapport à ça

je vois que lorsqu'on crée un texte dans MBM le texte sur la liste des notes apparait bien propre, mais pas au survol qui montre les codes des lettres accentuées et qqs espaces manquants.

![Capture d’écran 2020-05-07 à 08 03 42](https://user-images.githubusercontent.com/41069288/81260580-932e2800-903a-11ea-9399-95a6277e74f6.png)

**Comment by lzpons** [comment]
Autre test fait ce jour,
je crée deux notes une de ruche et l'autre de rucher sur MS et dès que je vais sur MBM (refresh de la page) elles apparaissent déjà corrompues. Donc c'est sur le chemin d'aller qu'il y a un soucis.

Vue MS
![vue MS](https://user-images.githubusercontent.com/41069288/83502012-461a6600-a4c1-11ea-86d9-c78326daa984.png)

Résultat MBM
![vue MBM](https://user-images.githubusercontent.com/41069288/83502018-47e42980-a4c1-11ea-8cd1-d88f2bb1631f.png)

**Comment by savioarthu** [comment]
A priori le MBM to MS fonctionne partout mais le MS To MBM ne fonctionne pas.
Quand on regarde plus en détails nos API (https://app.beekeeping.io/docs/mellisphera/#/Devices/Devices_GetReadings), on se rend compte qu"'il y a un GET, POST et PUT vers MBM

<img width="1492" alt="Capture d’écran 2020-06-06 à 11 01 44" src="https://user-images.githubusercontent.com/49641714/83940531-28ad0b00-a7e5-11ea-98dd-29b2c96599aa.png">

En cherchant un peu dans les fonctions, j'ai trouvé rapidement la fonction qui put les notes vers MBM. Cette fonction utilise la library gson qui convertit à priori un object java en json. 

Plusieurs sujets stackoverflow existe et mentionne un problème d'accent remplacé par un <?> avec cette méthode (https://stackoverflow.com/questions/14801546/gson-library-parse-json-utf-8-not-properly-replace-accent-by par exemple). Ce genre de sujet existe enormément. On peut alors penser que c'est également notre problème.

Plusieurs solutions sont proposées, dont je ne connais pas les effets et les utilités exactes. 

Voici la morceau de code en question

![Capture d’écran 2020-06-05 à 17 19 06](https://user-images.githubusercontent.com/49641714/83940581-85a8c100-a7e5-11ea-94e9-61580652b967.png)

Je pense que c'est la fonction 'putNote' qui est notre soucis. La ligne 'String noteJson = gson.toJson(bmNote)' est la ligne qui potentiellement pose problème.
En commentaire, j'ai écrit une potentielle solution 'byte [] newNoteJson = noteJson.getBytes("UTF-8")" qui faisait partie des propositions et donc par la suite il faudrait utilisait ce newNoteJson pour la requête. 
Cependant, je ne sais pas si cette ligne fonctionne et si tel est le cas résout notre problème, ce n'est qu'une aide pouvant pousser vers là ou on veut aller.

A determiner par un expert dans le domaine.

**Comment by lzpons** [comment]
Deep accent testing with Arthur.

POST (create note)
- notes are not properly encoded when sent to Mybroodminder through the java API
- hovewer using Advanced Rest Client the notes are properly sent 

PUT (update note)
- same issue : KO with java, OK with ARC.

=> Those tests clearly show that the encoding issue is related to java and how it sends the json payload.

**Comment by savioarthu** [comment]
Résolu !!
