### ISSUE TITLE
Texte et traduction des info bulle

### ISSUE THREAD

**Issue by mickael2407** [mellisphera/mellisphera-web#92]
### Ecrire dans les fichier de traduction les messages pour aider les future utilisateurs:

*  Cloner la branch **feature/help** de mellisphera-web : 
`git clone https://github.com/mellisphera/mellisphera-web.git --branch feature/help`

* Dans le répertoire *mellisphera-web/src/assets/i18n/*
* Modifier les fichiers de traduction:

**Pour melliUx :** 
```
    "MELLIUX": {
        "HELP": {
            "APIARY": {
                "APIARY_PICTURE": "",
                "EVENT_CALENDAR": ""
            },
            "HIVE": {
                "EVENT_CALENDAR": "",
                "BROOD_CALENDAR": "",
                "WEIGHT_CALENDAR": ""
            }
        }
    },
```

**Pour melliCharts :**
```
    "MELLICHARTS": {
        "HELP": {
            "BROOD": {
                
            }
        },
```

**Comment by lzpons** [comment]
@mickael2407 je viens de commiter les textes pour les infobulles. Dans Apiary, dans Explore et dans Alerts.
Après avoir revu leur positionnement je trouve qu'il faut systématiquement positionner ces infobulles en bas à droite.
- en bas à droite de la photo du rucher et de chaque calendrier dans APIARY
- en bas à droite de chaque page de EXPLORE pour hive / brood / raw (coin inférieur droit)
- en bas à droite de chaque page dans ALERTS (là pour le coup il va manquer des textes. Mets le même texte dans toutes les pages pour l'instant.

**Comment by lzpons** [comment]
Reste à revoir la longueur et les traduire en espagnol

**Comment by savioarthu** [comment]
J'ai ajouté les nouvelles trad FR + trad ES (il faudra quand même regarder si la trad n'est pas mauvaise) sur la branche feature/help (fr/en/es.json).

**Comment by savioarthu** [comment]
C'est fait. Pour l'instant, on laisse comme ça, on avisera avec le temps ;)
