### ISSUE TITLE
Bouton radio saute de nouveau dans les préférences

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#94]
Entre le choix de la langue et le choix des unités, les boutons radios sautent. 

<img width="281" alt="Radio preferences" src="https://user-images.githubusercontent.com/49641714/71361224-9c8a8c80-2592-11ea-8762-fee4067435c1.png">

**Comment by savioarthu** [comment]
Fonctionne pas chez moi :(

**Comment by mickael2407** [comment]
J'ai corrigé mais pas encore déployé

**Comment by lzpons** [comment]
ça marche pour moi. 
je ferme
