### ISSUE TITLE
Erreur de chargement sur bzz.mellisphera.com

### ISSUE THREAD

**Issue by savioarthu** [mellisphera/mellisphera-web#95]
On en a déjà parlé avec @mickael2407  mais c'est quand même important, je crée une issue. 

Quand j'ajoute bzz.mellisphera.com à mes favoris sur la page de login, impossible de revenir sur la page ensuite (je dois enlever le /login). Idem si je le fais une fois connecté. Impossible de rafraîchir une page ou ajouter aux favoris le site, j'arrive sur cette page à chaque fois;

<img width="471" alt="Capture d’écran 2019-12-27 à 12 38 22" src="https://user-images.githubusercontent.com/49641714/71515859-fdbda300-28a5-11ea-92c0-8324f6ede7ea.png">
<img width="258" alt="Capture d’écran 2019-12-27 à 12 38 28" src="https://user-images.githubusercontent.com/49641714/71515860-fe563980-28a5-11ea-87b7-3db448653d45.png">
<img width="364" alt="Capture d’écran 2019-12-27 à 12 38 41" src="https://user-images.githubusercontent.com/49641714/71515861-fe563980-28a5-11ea-8dea-86ae946f90d0.png">

**Comment by lzpons** [comment]
J'espère que @mickael2407 a une idée car moi je suis sec.
c'est une histoire avec Apache... on a déjà vu par le passé il me semble..

**Comment by mickael2407** [comment]
C'est un problème avec le fichier htaccess de apache j'ai mis le même que sur test donc normalement cela devrait fonctionner j'avais eu des soucis avants j'y réfléchis

**Comment by savioarthu** [comment]
Malheureusement ça ne fonctionne toujours pas :(

**Comment by savioarthu** [comment]
Fonctionne 👍
