### ISSUE TITLE
Ajustements sur module alertes

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#96]
Après l'implémentation de @mickael2407 voici quelques petits ajustements.

1/ Organiser les boutons ainsi : hive / weather / sensor / settings (au lieu de configure)
![Capture d’écran 2019-12-27 à 12 38 12](https://user-images.githubusercontent.com/41069288/71515824-c0f1ac00-28a5-11ea-899d-1c5ffeeed6af.png)

2/ Déplacer "high int humid" et "low int humid" dans le menu Hive. Même chose pour High/Low internal temperature.

3/ "stolen hive" irait également dans sensor

4/ reorganiser un peu les settings
avec les boutons on/off sur la première ligne et justifiés à droite comme pour le reste des alertes.
avec le libellé "email 1" dans la case 
avec une deuxième case pour un "email 2"
remplacer frequency (mot barbare d'ingénieur) pas "send every" : day, week, every x days
espacer le texte du bouton radio !!

![Capture d’écran 2019-12-27 à 12 43 28](https://user-images.githubusercontent.com/41069288/71516006-cd2a3900-28a6-11ea-9efc-3bd647235968.png)
je sais que c'est pas tout à fait ce que j'avais marqué dans la spec!, c'est en le voyant fait qu'on percute mieux, sorry, sorry.

**Comment by savioarthu** [comment]
Pour moi c'est bon.
Peut-être juste pour que ça soit en concordance totale :
1) mettre une miniscule à 'Every'/'Tout'/'Cada' 
2) espacer le 'every/'tout'/'cada' du bouton radio. 
3) 'Tout' s'écrit 'Tous' avec un 's' en FR. 
4) Peut-être écrire à la fin 'day(s)/jour(s)/dia(s)' car ça sera sûrement au pluriel souvent.
5) Rapprocher le bouton 'On/off' au même niveau que les autres pages.
6) Et du coup y aura peut-etre besoin de descrendre un peu les emails pour que le bouton On/off soit bien en face du texte ? 
7) Peut-etre réduire la taille de l'encart (par 2 je dirais) pour écrire les emails aussi ? 

Enfin bref que des petits détails

**Comment by savioarthu** [comment]
Et ne pas oublier de rajouter dans météo l'alerte 'StopWeather' pour les gens qui ont une station météo -> pour nos ça correspond uniquement au compte lorenzo.pons. (voir issue #93)

**Comment by savioarthu** [comment]
Je ferme ici car l'issue #102 relate de ces points là !
