### ISSUE TITLE
Premier lundi du mois ne se remplit pas?

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#98]
1a/ Je viens de créer un document dans DailyRecordsTH pour le 25/11 comme pour les autres jours qui n'en avaient pas, mais celui ci ne s'affiche pas dans Apiary alors que dans Explore il apparait. C'est étrange.

![Capture d’écran 2019-12-28 à 21 53 01](https://user-images.githubusercontent.com/41069288/71549392-d0174d80-29bc-11ea-9a6d-6f133a9124a8.png)

![Capture d’écran 2019-12-28 à 21 52 49](https://user-images.githubusercontent.com/41069288/71549394-d1487a80-29bc-11ea-9577-18c483928b3b.png)

1b/ Même chose pour la productivité, lundi existe (j'ai vérifié) mais n'apparait pas 
![Capture d’écran 2019-12-28 à 22 31 45](https://user-images.githubusercontent.com/41069288/71549689-fd1a2f00-29c1-11ea-80fd-efb26fb0b8cf.png)

2/ Un peu dans la même série, je constate également que le lundi 28/10 est rempli dans le premier écran mais pas dans le deuxième lorsque je remonte dans le temps avec la flèche.
On s'attendrait également a démarrer le calendrier un lundi et à le terminer toujours un samedi si on remonte des périodes entières non?

![Capture d’écran 2019-12-28 à 22 02 15](https://user-images.githubusercontent.com/41069288/71549454-e671d900-29bd-11ea-9f1b-f35d9edb2132.png)

![Capture d’écran 2019-12-28 à 22 02 04](https://user-images.githubusercontent.com/41069288/71549455-e7a30600-29bd-11ea-86c8-000f4fd7cc7a.png)
Il doit y avoir une coquille dans le calcul du nombre de jours.

**Comment by savioarthu** [comment]
Reste le soucis du 1a) -> manque les premiers lundi dans MelliUx

**Comment by mickael2407** [comment]
Pour moi les lundi sont bien remplie
