### ISSUE TITLE
La plage calendaire n'est pas respectée

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#99]
Dans le module Explore lorsqu'on choisit une plage de 1 mois on en a 2, lorsqu'on choisit 2 il y en a 3 et pour 3 on en trouve 4.

**Comment by mickael2407** [comment]
Voila en incluant la logique de toujours faire commencer les jours des calendrier un Lundi avec la méthode qui fonctionne très bien dans melliUx mais dans melliCharts on se retrouve avec des changements de date.
J'ai donc modifié pour faire autrement mais il y aura toujours des décalage avec la date sélectionner

**Comment by savioarthu** [comment]
Ca marche plutôt bien chez moi malgré tout !

**Comment by mickael2407** [comment]
Du coup on ferme ??
